/* PLEX PLAY · lecciones nuevas del curso prog (las carga js/plx66.js) */
(function(){var M=window.PLXM;if(!M)return;var C=M.C,A=M.A,F=M.F,Mt=M.M,S=M.S,P=M.P,O=M.O,D=M.D,L=M.L,U=M.U,Sec=M.Sec;
var S7=Sec("C1.1·7","Syntaxe et style de l'écrit C1","Aposición, participiales, infinitivo sujeto, concesión rara, hipótesis sin si, elipsis, modalización académica, tiempos del texto académico, negaciones literarias y verbos académicos.",[
U("Condensar la frase",[
L("prog-apposition","L'apposition et le détachement","synt",{
 idea:"La aposición añade información sobre un nombre, separada por comas, sin verbo conjugado: Victor Hugo, écrivain engagé, s'exila à Guernesey. También se anteponen adjetivos o participios: Fatigués, les étudiants sont rentrés. Condensa y da ritmo al texto académico.",
 para:"Para escribir frases densas y elegantes sin acumular relativas.",
 regla:["Nombre en aposición: <i>Marie Curie, <b>physicienne</b> d'origine polonaise, …</i>","Adjetivo / participio antepuesto: <i><b>Convaincu</b> de son erreur, il s'excusa.</i>","El elemento apuesto debe referirse al <b>sujeto</b> de la principal.","Sustituye relativas: <i>Paris, qui est la capitale…</i> → <i>Paris, capitale…</i>","Siempre entre comas."],
 ej:[["Descartes, philosophe du XVIIe siècle, a fondé le rationalisme.","Descartes, filósofo del siglo XVII, fundó el racionalismo."],["Inquiets, les habitants ont quitté le quartier.","Preocupados, los habitantes dejaron el barrio."],["Ce phénomène, longtemps ignoré, suscite aujourd'hui l'intérêt.","Este fenómeno, largo tiempo ignorado, suscita hoy interés."]],
 ojo:["Arrivé à la gare, le train était parti.","Arrivé à la gare, j'ai constaté que le train était parti.","El apuesto debe referirse al <b>sujeto</b>."]},[
 C("Elige la versión con aposición.","Paris, qui est la capitale de la France, attire…",["Paris, capitale de la France, attire…","Paris, la qui capitale, attire…","Paris capitale est de la France, attire…"],0,"Sin verbo: <b>aposición</b>."),
 C("¿Cuál es correcta?","Participio antepuesto",["Épuisée, elle s'est endormie.","Épuisée, le sommeil l'a prise.","Épuisé, elle s'est endormie."],0,"Se refiere al sujeto <i>elle</i>."),
 C("¿Qué signo rodea la aposición?","Puntuación",["comas","punto y coma","comillas"],0,"<b>Comas</b>."),
 F("Completa con un nombre en aposición.","Einstein, ___ de génie, a révolutionné la physique. (físico)",["physicien"],"<b>physicien</b>."),
 F("Completa con el participio.","___ par la critique, le film a pourtant eu du succès. (criticado)",["Critiqué"],"<b>Critiqué</b>."),
 Mt("Une cada relativa con su aposición.","Relativa → aposición",[["Lyon, qui est une ville gastronomique,","Lyon, ville gastronomique,"],["Le rapport, qui a été publié hier,","Le rapport, publié hier,"],["Anne, qui était inquiète,","Inquiète, Anne"],["Ce projet, qui est ambitieux,","Ce projet ambitieux"]],"Condensar."),
 S("Clasifica.","¿Correcta?",["Correcta","Incorrecta (sujeto distinto)"],[["Arrivé tôt, il a attendu.",0],["Surprise, elle n'a rien dit.",0],["Rédigé en 1850, ce texte reste actuel.",0],["Fatigués, nous sommes rentrés.",0],["Arrivé tôt, la porte était fermée.",1],["Surprise, le silence s'installa.",1],["Rédigé en 1850, l'auteur le publia.",1],["Fatigués, la route semblait longue.",1]],"El sujeto debe coincidir."),
 P("Encuentra la palabra incorrecta y corrígela.","[Inquiet] , les chercheuses ont interrompu l'expérience .","Inquiètes","Concuerda con <i>chercheuses</i>: <b>Inquiètes</b>."),
 O("Ordena: «Marie Curie, física polaca, ganó dos Nobel».",["Marie Curie,","physicienne polonaise,","a obtenu","deux prix Nobel"],"<i>Marie Curie, physicienne polonaise, a obtenu deux prix Nobel.</i>"),
 D("Longtemps ignoré, ce phénomène suscite aujourd'hui l'intérêt des chercheurs.")]),
L("prog-participiale","La proposition participiale : le travail terminé, il partit","synt",{
 idea:"La participial tiene su propio sujeto, distinto del de la principal, y expresa tiempo o causa: Le travail terminé, les ouvriers rentrèrent. La nuit tombant, nous avons allumé un feu. Es propia del registro escrito cuidado.",
 para:"Para variar la sintaxis y expresar circunstancias con concisión.",
 regla:["<b>sujeto + participio pasado</b>: anterioridad: <i>Les examens terminés, les étudiants partirent.</i>","<b>sujeto + participio presente</b>: simultaneidad o causa: <i>Le temps pressant, il fallut décider.</i>","Sujeto <b>distinto</b> del de la principal.","Equivalencias: <i>Une fois les examens terminés…, Comme le temps pressait…</i>"],
 ej:[["La réunion terminée, chacun est rentré chez soi.","Terminada la reunión, cada uno volvió a su casa."],["Le budget étant limité, le projet a été réduit.","Siendo limitado el presupuesto, se redujo el proyecto."],["Dieu aidant, tout ira bien.","Con la ayuda de Dios, todo irá bien."]],
 ojo:["Terminée la réunion, …","La réunion terminée, …","En francés el sujeto va <b>delante</b> del participio."]},[
 C("Elige la participial correcta.","Terminada la clase…",["Le cours terminé, …","Terminé le cours, …","Le cours terminant, … (anterior)"],0,"<b>sujeto + participio</b>."),
 C("¿Qué expresa?","La pluie tombant, le match fut annulé.",["causa","finalidad","concesión"],0,"<b>Causa</b>."),
 C("Elige la equivalencia.","Les invités partis, nous avons rangé.",["Une fois que les invités sont partis, nous avons rangé.","Pour que les invités partent, nous avons rangé.","Bien que les invités soient partis, nous avons rangé."],0,"<b>Anterioridad</b>."),
 F("Completa con el participio.","Le contrat ___ , les travaux ont commencé. (firmado)",["signé"],"<b>signé</b>."),
 F("Completa con el participio presente.","Le temps ___ , nous avons dû abréger. (apremiar: presser)",["pressant"],"<b>pressant</b>."),
 Mt("Une cada participial con su equivalente.","Participial → subordinada",[["Le repas fini,","Quand le repas fut fini,"],["La nuit tombant,","Comme la nuit tombait,"],["Les résultats publiés,","Après la publication des résultats,"],["Le budget étant serré,","Parce que le budget était serré,"]],"Equivalencias."),
 S("Clasifica.","¿Participial o gerundio?",["Participial (sujeto propio)","Gerundio (mismo sujeto)"],[["Le soleil se levant, …",0],["La décision prise, …",0],["Les élèves partis, …",0],["Son travail achevé, …",0],["En partant, il a salué.",1],["En lisant, j'ai compris.",1],["En arrivant, elle a souri.",1],["En travaillant, on progresse.",1]],"¿Quién hace la acción?"),
 P("Encuentra la palabra incorrecta y corrígela.","Les résultats [publié] , le ministre a réagi immédiatement .","publiés","Concuerda con <i>résultats</i>: <b>publiés</b>."),
 O("Ordena: «Terminado el trabajo, se fueron».",["Le travail","terminé,","ils","sont partis"],"<i>Le travail terminé, ils sont partis.</i>"),
 D("Les examens terminés, les étudiants sont partis en vacances.")]),
L("prog-infinitif-nom","L'infinitif sujet et nominal : comprendre, c'est pardonner","synt",{
 idea:"El infinitivo puede funcionar como un nombre: sujeto (Voyager forme la jeunesse), atributo (Comprendre, c'est pardonner) o complemento. Da a las frases un tono general y sentencioso, útil en ensayos y conclusiones.",
 para:"Para formular ideas generales con elegancia.",
 regla:["Infinitivo sujeto: <i><b>Lire</b> développe l'imagination.</i>","Estructura de relieve: <i><b>Apprendre une langue</b>, c'est s'ouvrir au monde.</i>","Tras <i>c'est</i>: <i>Le plus difficile, c'est <b>de commencer</b>.</i>","Sin artículo (≠ español «el leer»).","Con negación: <i><b>Ne pas</b> agir serait une erreur.</i>"],
 ej:[["Voyager permet de mieux se connaître.","Viajar permite conocerse mejor."],["Enseigner, c'est apprendre deux fois.","Enseñar es aprender dos veces."],["Ne rien faire serait irresponsable.","No hacer nada sería irresponsable."]],
 ojo:["Le lire est important.","Lire est important.","Sin artículo."]},[
 C("Elige.","Leer es un placer.",["Lire est un plaisir.","Le lire est un plaisir.","De lire est un plaisir."],0,"<b>Infinitivo sujeto</b> sin artículo."),
 C("Elige la negación.","No actuar sería un error.",["Ne pas agir serait une erreur.","Ne agir pas serait une erreur.","Pas agir ne serait une erreur."],0,"<b>ne pas</b> delante del infinitivo."),
 C("Elige.","Lo más difícil es empezar.",["Le plus difficile, c'est de commencer.","Le plus difficile, c'est commencer de.","Le plus difficile est que commencer."],0,"<b>c'est de</b> + infinitivo."),
 F("Completa.","___ , c'est pardonner. (comprender)",["Comprendre"],"<b>Comprendre</b>."),
 F("Completa.","Ne ___ comprendre est parfois frustrant.",["pas"],"<b>ne pas</b>."),
 Mt("Une cada comienzo con su final.","Infinitivo → idea",[["Voyager,","c'est découvrir l'autre."],["Enseigner,","c'est apprendre deux fois."],["Écrire,","c'est penser sur le papier."],["Douter,","c'est déjà réfléchir."]],"Sentencias."),
 S("Clasifica.","¿Correcta?",["Correcta","Incorrecta"],[["Lire enrichit l'esprit.",0],["Ne pas répondre est impoli.",0],["Partir, c'est mourir un peu.",0],["Le mieux est d'attendre.",0],["Le lire enrichit l'esprit.",1],["Ne répondre pas est impoli.",1],["Le partir, c'est mourir un peu.",1],["Le mieux est attendre de.",1]],"Sin artículo; negación delante."),
 P("Encuentra la palabra incorrecta y corrígela.","[Le] voyager forme la jeunesse , dit le proverbe .","Voyager","Sin artículo: <b>Voyager</b> forme…"),
 O("Ordena: «Aprender una lengua es abrirse al mundo».",["Apprendre une langue,","c'est","s'ouvrir","au monde"],"<i>Apprendre une langue, c'est s'ouvrir au monde.</i>"),
 D("Apprendre une langue étrangère, c'est accepter de se tromper.")]),
L("prog-concession-rare","Concession soutenue : quelque… que, si… que, tout… que","synt",{
 idea:"El registro culto tiene estructuras concesivas con subjuntivo: quelque + adjetivo + que (por muy… que), si + adjetivo + que, pour + adjetivo + que; tout + adjetivo + que (con indicativo); quel(le)(s) que soit (sea cual sea); qui que ce soit, quoi que ce soit.",
 para:"Para matizar concesiones en textos académicos y literarios.",
 regla:["<b>si / aussi / quelque / pour + adj. + que + subjuntivo</b>: <i>Si difficile que soit la tâche…</i>","<b>tout + adj. + que + indicativo</b>: <i>Tout riche qu'il est, il reste modeste.</i>","<b>quel(le)(s) que + être en subj.</b>: <i>Quelle que soit ta décision…</i> (concuerda con el sujeto).","<b>qui que / quoi que / où que + subj.</b>: <i>Où que tu ailles…</i>","<i>quelque</i> aquí es adverbio: invariable."],
 ej:[["Si compétent qu'il soit, il ne peut pas tout faire.","Por muy competente que sea, no puede hacerlo todo."],["Quelle que soit la solution, elle aura un coût.","Sea cual sea la solución, tendrá un coste."],["Où que tu ailles, je te suivrai.","Vayas donde vayas, te seguiré."]],
 ojo:["Quelque soit la raison…","Quelle que soit la raison…","Concuerda con <i>raison</i>: <b>Quelle que</b>, en dos palabras."]},[
 C("Elige.","Sea cual sea el precio…",["Quel que soit le prix…","Quelque soit le prix…","Quelle que soit le prix…"],0,"<i>Prix</i> masc.: <b>Quel que soit</b>."),
 C("Elige.","Por muy inteligente que sea…",["Si intelligent qu'il soit…","Si intelligent qu'il est…","Si intelligent que il sera…"],0,"<b>si… que + subj.</b>"),
 C("Elige.","Vayas donde vayas…",["Où que tu ailles…","Où que tu vas…","Partout que tu ailles…"],0,"<b>où que + subj.</b>"),
 F("Completa.","___ que soient les difficultés, nous continuerons. (fem. pl.)",["Quelles"],"<b>Quelles que</b>."),
 F("Completa con el indicativo.","Tout fatigué qu'il ___ , il a terminé le travail. (être)",["est","était"],"<b>tout… que + indicativo</b>."),
 Mt("Une cada estructura con su modo.","Estructura → modo",[["si… que","subjuntivo"],["tout… que","indicativo"],["quel que soit","être en subjuntivo"],["quoi que","subjuntivo (quoi que)"]],"Modos."),
 S("Clasifica.","¿Forma correcta?",["Correcta","Incorrecta"],[["Quelle que soit l'heure",0],["Quels que soient les risques",0],["Si grand qu'il soit",0],["Quoi que tu dises",0],["Quelque soit l'heure",1],["Quelques soient les risques",1],["Si grand qu'il est",1],["Quoique tu dises (= sea lo que sea)",1]],"Ortografía y modo."),
 P("Encuentra la palabra incorrecta y corrígela.","[Quelque] soit votre décision , nous la respecterons .","Quelle","<i>Décision</i> fem.: <b>Quelle</b> que soit."),
 O("Ordena: «Por difícil que sea, lo lograremos».",["Si difficile","que ce soit,","nous","y arriverons"],"<i>Si difficile que ce soit, nous y arriverons.</i>"),
 D("Quelles que soient les critiques, les chercheurs poursuivront leurs travaux.")])
]),
U("Matizar el razonamiento",[
L("prog-hypothese-sans-si","L'hypothèse sans si : viendrait-il, pour peu que, à supposer que","synt",{
 idea:"En registro culto la hipótesis se expresa sin si: inversión con condicional (Viendrait-il à échouer, nous l'aiderions), yuxtaposición (Tu me l'aurais dit, je serais venu), pour peu que / à supposer que / en admettant que + subjuntivo, gérondif (En partant tôt, tu arriveras).",
 para:"Para variar la expresión de la hipótesis en textos avanzados.",
 regla:["<b>Inversión + condicional</b>: <i>Serait-il absent, la réunion aurait lieu.</i>","<b>Yuxtaposición</b> de dos condicionales: <i>Il viendrait, je serais ravi.</i>","<b>pour peu que / à supposer que / en admettant que / pourvu que + subj.</b>","<b>à moins de + inf.</b> / <b>à condition de + inf.</b>","<b>Gerundio</b>: <i>En travaillant, tu réussiras.</i>"],
 ej:[["Pour peu qu'il fasse beau, nous sortirons.","Por poco que haga buen tiempo, saldremos."],["À supposer que l'hypothèse soit vraie, que se passerait-il ?","Suponiendo que la hipótesis sea cierta, ¿qué pasaría?"],["Aurait-il accepté, tout aurait été différent.","De haber aceptado, todo habría sido diferente."]],
 ojo:["À supposer que l'hypothèse est vraie","À supposer que l'hypothèse soit vraie","<b>+ subjuntivo</b>."]},[
 C("Elige.","Suponiendo que sea verdad…",["À supposer que ce soit vrai…","À supposer que c'est vrai…","À supposer que ce serait vrai…"],0,"<b>+ subjuntivo</b>."),
 C("¿Qué expresa?","Pour peu qu'on l'encourage, il progresse.",["una condición mínima suficiente","una finalidad","una oposición"],0,"<b>Por poco que</b>."),
 C("Elige la inversión hipotética.","Si fallara…",["Viendrait-il à échouer, …","Vient-il à échouer si, …","Il viendrait-il échouer, …"],0,"<b>Inversión + condicional</b>."),
 F("Completa.","En ___ que tu aies raison, que proposes-tu ? (admitiendo)",["admettant"],"<b>En admettant que</b>."),
 F("Completa con el subjuntivo.","Pour peu qu'il ___ un effort, il réussira. (faire)",["fasse"],"<b>fasse</b>."),
 Mt("Une cada estructura con su construcción.","Estructura → modo",[["à supposer que","+ subjuntivo"],["au cas où","+ condicional"],["à moins de","+ infinitivo"],["en + participio presente","gerundio"]],"Hipótesis sin si."),
 S("Clasifica.","Modo",["Subjuntivo","Condicional"],[["pour peu que",0],["à supposer que",0],["en admettant que",0],["pourvu que",0],["au cas où",1],["dans l'hypothèse où",1],["quand bien même",1],["inversion (Serait-il…)",1]],"Qué sigue."),
 P("Encuentra la palabra incorrecta y corrígela.","À supposer que cette théorie [est] exacte , il faudrait revoir le modèle .","soit","<b>soit</b> (subjuntivo)."),
 O("Ordena: «Suponiendo que tenga razón».",["À supposer","qu'il","ait","raison"],"<i>À supposer qu'il ait raison.</i>"),
 D("Pour peu que les conditions soient réunies, l'expérience pourra être reproduite.")]),
L("prog-ellipse","Ellipse, parallélisme et rythme de la phrase","synt",{
 idea:"La elipsis suprime elementos repetidos (Pierre aime le jazz ; Marie, la musique classique). El paralelismo repite una estructura para dar ritmo y claridad (non seulement…, mais aussi…; plus…, plus…). El texto académico C1 busca frases equilibradas y sin redundancias.",
 para:"Para escribir con concisión y ritmo.",
 regla:["Elipsis del verbo con coma: <i>Les uns votent à gauche ; les autres, à droite.</i>","Paralelismo gramatical: mismas categorías coordinadas: <i>apprendre, comprendre et appliquer</i> (no mezclar nombre + infinitivo).","Estructuras correlativas: <i>plus… plus, autant… autant, soit… soit, ni… ni</i>.","Ternario: tres elementos para cerrar con fuerza."],
 ej:[["Plus on lit, plus on apprend.","Cuanto más se lee, más se aprende."],["Les uns travaillent ; les autres, non.","Unos trabajan; otros, no."],["Il faut informer, former et accompagner.","Hay que informar, formar y acompañar."]],
 ojo:["Il faut l'information, former et accompagner.","Il faut informer, former et accompagner.","Paralelismo: <b>misma categoría</b>."]},[
 C("Elige la frase con paralelismo correcto.","Enumeración",["Ce projet vise à informer, sensibiliser et agir.","Ce projet vise l'information, sensibiliser et l'action.","Ce projet vise à informer, la sensibilisation et agir."],0,"Tres infinitivos."),
 C("Elige.","Cuanto más trabajo, más aprendo.",["Plus je travaille, plus j'apprends.","Plus je travaille, le plus j'apprends.","Le plus je travaille, plus j'apprends."],0,"<b>plus… plus</b> sin artículo."),
 C("¿Qué se ha elidido?","Paul aime le thé ; Anne, le café.",["el verbo «aime»","el sujeto","el artículo"],0,"Elipsis del <b>verbo</b>."),
 F("Completa.","___ on attend, moins on a de choix.",["Plus"],"<b>Plus… moins</b>."),
 F("Completa.","Les uns applaudissent ; les ___ , sifflent.",["autres"],"<b>les autres</b>."),
 Mt("Une cada correlación con su sentido.","Francés → español",[["plus… plus","cuanto más… más"],["autant… autant","tanto… como"],["soit… soit","o… o"],["ni… ni","ni… ni"]],"Estructuras correlativas."),
 S("Clasifica.","¿Paralelismo correcto?",["Correcto","Incorrecto"],[["lire, écrire et compter",0],["la santé, l'éducation et le logement",0],["rapide, efficace et économique",0],["comprendre et agir",0],["lire, l'écriture et compter",1],["la santé, éduquer et le logement",1],["rapide, efficacement et économique",1],["comprendre et l'action",1]],"Misma categoría."),
 P("Encuentra la palabra incorrecta y corrígela.","Ce programme permet de former , d'informer et l'[accompagnement] des jeunes .","accompagner","Paralelismo: <b>d'accompagner</b>."),
 O("Ordena: «Cuanto más se lee, más se aprende».",["Plus","on lit,","plus","on apprend"],"<i>Plus on lit, plus on apprend.</i>"),
 D("Les uns réclament plus de liberté ; les autres, plus de sécurité.")]),
L("prog-modalisation-c1","Modaliser son discours académique","registre",{
 idea:"El discurso académico matiza sus afirmaciones según el grado de certeza: force est de constater que (hay que reconocer), il semblerait que, il apparaît que, on peut supposer que, il n'est pas exclu que, selon toute vraisemblance, dans une large mesure.",
 para:"Para escribir con prudencia científica en síntesis y ensayos.",
 regla:["Certeza: <i>force est de constater que, il est indéniable que, il ressort de… que</i> (+ ind.).","Probabilidad: <i>selon toute vraisemblance, il est probable que, il apparaît que</i> (+ ind.).","Posibilidad: <i>il se pourrait que, il n'est pas exclu que, on peut supposer que</i> (subj. en las dos primeras).","Limitación: <i>dans une large mesure, dans une certaine mesure, en partie</i>.","Condicional de prudencia: <i>il semblerait que, on pourrait avancer que</i>."],
 ej:[["Force est de constater que les inégalités se creusent.","Hay que reconocer que las desigualdades se agrandan."],["Il n'est pas exclu que les résultats soient faussés.","No se excluye que los resultados estén falseados."],["Il ressort de cette étude que…","De este estudio se desprende que…"]],
 ojo:["Force est de constater qu'il soit…","Force est de constater qu'il est…","Certeza → <b>indicativo</b>."]},[
 C("¿Qué grado expresa «force est de constater»?","Grado",["certeza","duda","deseo"],0,"<b>Certeza</b>."),
 C("Elige.","No se excluye que…",["Il n'est pas exclu que + subj.","Il n'est pas exclu que + ind. futuro siempre","Il est pas exclu de que"],0,"<b>+ subjuntivo</b>."),
 C("Elige.","Se desprende de este estudio que…",["Il ressort de cette étude que…","Il sort de cette étude que…","Il ressorte cette étude de que…"],0,"<b>il ressort de</b>."),
 F("Completa.","Selon toute ___ , la tendance se poursuivra. (probabilidad)",["vraisemblance"],"<b>selon toute vraisemblance</b>."),
 F("Completa con el subjuntivo.","Il se pourrait que les chiffres ___ sous-estimés. (être)",["soient"],"<b>soient</b>."),
 Mt("Une cada fórmula con su grado.","Fórmula → grado",[["il est indéniable que","certeza"],["selon toute vraisemblance","probabilidad"],["il se pourrait que","posibilidad"],["dans une certaine mesure","limitación"]],"Escala de modalización."),
 S("Clasifica.","Modo tras la fórmula",["Indicativo","Subjuntivo"],[["force est de constater que",0],["il apparaît que",0],["il ressort que",0],["il est indéniable que",0],["il se pourrait que",1],["il n'est pas exclu que",1],["il est possible que",1],["il semble que",1]],"Certeza frente a posibilidad."),
 P("Encuentra la palabra incorrecta y corrígela.","Force est de constater que la situation [soit] préoccupante .","est","Certeza: <b>est</b>."),
 O("Ordena: «Hay que reconocer que…».",["Force","est","de constater","que…"],"<i>Force est de constater que…</i>"),
 D("Il ressort de cette enquête que les jeunes s'informent surtout en ligne.")]),
L("prog-temps-academique","Les temps du texte académique","conj",{
 idea:"En el texto académico predominan el presente de verdad general y de comentario (L'auteur montre que…), el passé composé para resultados de estudios (Les chercheurs ont observé…) y el condicional de prudencia. El futuro anuncia el plan (Nous verrons…). El passé simple se reserva a la narración histórica formal.",
 para:"Para elegir tiempos coherentes en resúmenes, síntesis y ensayos.",
 regla:["<b>Presente</b>: comentar un texto o afirmar un hecho general: <i>L'auteur souligne…</i>","<b>Passé composé</b>: resultados, hechos pasados vinculados al presente.","<b>Futuro / futuro próximo</b>: anunciar el plan: <i>Nous examinerons…</i>","<b>Condicional</b>: prudencia, información no confirmada.","Coherencia: no cambiar de tiempo sin razón."],
 ej:[["Dans cet article, l'auteur défend l'idée que…","En este artículo, el autor defiende la idea de que…"],["Une étude récente a montré que…","Un estudio reciente ha mostrado que…"],["Nous verrons d'abord…, puis nous analyserons…","Veremos primero…, luego analizaremos…"]],
 ojo:["L'auteur montrait / montra que…","L'auteur montre que…","Comentario: <b>presente</b>."]},[
 C("Elige el tiempo para comentar un texto.","El autor afirma que…",["L'auteur affirme que…","L'auteur affirma que…","L'auteur affirmerait que (seguro)…"],0,"<b>Presente</b>."),
 C("Elige para anunciar el plan.","Anunciar",["Nous examinerons d'abord…","Nous examinâmes d'abord…","Nous examinions d'abord…"],0,"<b>Futuro</b>."),
 C("Elige para un resultado de estudio.","Resultado",["Les chercheurs ont observé…","Les chercheurs observeraient hier…","Les chercheurs observèrent demain…"],0,"<b>Passé composé</b>."),
 F("Completa en presente.","Dans ce texte, la journaliste ___ les effets du télétravail. (analizar)",["analyse"],"<b>analyse</b>."),
 F("Completa en futuro.","Dans une seconde partie, nous ___ les limites. (ver)",["verrons"],"<b>verrons</b>."),
 Mt("Une cada uso con su tiempo.","Uso → tiempo",[["comentar el texto","presente"],["resultado de estudio","passé composé"],["anunciar el plan","futuro"],["dato no confirmado","condicional"]],"Coherencia temporal."),
 S("Clasifica.","¿Adecuado en un resumen académico?",["Adecuado","Inadecuado"],[["L'auteur montre que…",0],["Il souligne ensuite…",0],["Une étude a révélé…",0],["Nous verrons que…",0],["L'auteur montra hier…",1],["Il soulignait demain…",1],["Une étude révélait-elle…",1],["Nous vîmes que…",1]],"Tiempos académicos."),
 P("Encuentra la palabra incorrecta y corrígela.","Dans son article , l'auteur [défendit] une thèse originale .","défend","Comentario: presente <b>défend</b>."),
 O("Ordena: «El autor subraya que…».",["L'auteur","souligne","que…"],"<i>L'auteur souligne que…</i>"),
 D("Dans cet article, l'auteure montre que les réseaux sociaux transforment l'information.")])
]),
U("Léxico y estilo cultos",[
L("prog-negations-litteraires","Négations soutenues : ne… guère, ne… point, nul, aucunement","synt",{
 idea:"El registro culto usa negaciones especiales: ne… guère (apenas), ne… point (no, literario), nul(le) (ningún), aucunement / nullement (en absoluto), ne… que trop (demasiado bien), ni… ni… ne. También ne sin pas con cesser, oser, pouvoir, savoir: Il ne cesse de pleuvoir.",
 para:"Para comprender textos cultos y dar variedad a tu escritura.",
 regla:["<b>ne… guère</b> = apenas, casi no: <i>Il ne sort guère.</i>","<b>ne… point</b> = ne… pas (literario).","<b>nul(le)</b> determinante: <i>Nul doute que…, sans nul doute</i>.","<b>aucunement / nullement</b> = de ningún modo.","<b>ne</b> solo con <i>cesser, oser, pouvoir, savoir</i>: <i>Je ne saurais dire. Il n'ose parler.</i>"],
 ej:[["Il ne reste guère de temps.","Apenas queda tiempo."],["Nul n'est censé ignorer la loi.","Nadie puede alegar ignorancia de la ley."],["Je ne suis nullement convaincu.","No estoy en absoluto convencido."]],
 ojo:["Il ne cesse pas de pleuvoir (correcto) / Il ne cesse de pleuvoir (culto)","Ambas existen","Sin <i>pas</i> es más culto."]},[
 C("¿Qué significa «ne… guère»?","Il ne mange guère.",["apenas come","no come nunca","come mucho"],0,"<b>apenas</b>."),
 C("¿Qué significa?","Nul n'est parfait.",["Nadie es perfecto.","Lo nulo es perfecto.","Nada es imperfecto."],0,"<b>Nul</b> = nadie."),
 C("Elige la versión culta.","No sabría decirle.",["Je ne saurais vous dire.","Je ne saurais pas vous dire pas.","Je sais pas vous dire."],0,"<b>ne</b> solo con <i>savoir</i>."),
 F("Completa.","Je ne suis ___ d'accord avec cette idée. (en absoluto)",["nullement","aucunement","point"],"<b>nullement</b>."),
 F("Completa.","Sans ___ doute, c'est le meilleur roman de l'année.",["nul"],"<b>sans nul doute</b>."),
 Mt("Une cada negación con su sentido.","Francés → español",[["ne… guère","apenas"],["ne… point","no (literario)"],["nullement","en absoluto"],["nul","ninguno / nadie"]],"Negaciones cultas."),
 S("Clasifica.","Registro",["Culto / literario","Corriente"],[["ne… point",0],["ne… guère",0],["nul n'ignore",0],["il n'ose parler",0],["ne… pas",1],["presque pas",1],["personne n'ignore",1],["il n'ose pas parler",1]],"Equivalentes."),
 P("Encuentra la palabra incorrecta y corrígela.","[Nulle] n'est censé ignorer la loi .","Nul","Pronombre masculino genérico: <b>Nul</b>."),
 O("Ordena: «Apenas queda tiempo».",["Il","ne reste","guère","de temps"],"<i>Il ne reste guère de temps.</i>"),
 D("Nul ne saurait nier l'importance de cette découverte.")]),
L("prog-verbes-academiques","Les verbes de l'analyse : souligner, mettre en évidence, nuancer","registre",{
 idea:"Para describir lo que hace un autor o un documento se usan verbos precisos: analyser, examiner, mettre en évidence (poner de relieve), souligner, nuancer, remettre en question, s'interroger sur, aborder, étayer (apoyar con pruebas), réfuter, illustrer.",
 para:"Para resumir, sintetizar y comentar documentos en el DALF.",
 regla:["Presentar: <i>aborder, traiter de, porter sur, s'intéresser à</i>.","Mostrar: <i>mettre en évidence, mettre en lumière, révéler, démontrer</i>.","Destacar: <i>souligner, insister sur, mettre l'accent sur</i>.","Discutir: <i>nuancer, remettre en question / en cause, s'interroger sur, réfuter</i>.","Apoyar: <i>étayer, illustrer, justifier, appuyer</i>."],
 ej:[["Cette étude met en évidence un lien entre sommeil et réussite.","Este estudio pone de relieve un vínculo entre sueño y éxito."],["L'auteur étaye sa thèse par des exemples historiques.","El autor apoya su tesis con ejemplos históricos."],["Le second document nuance ce constat.","El segundo documento matiza esta constatación."]],
 ojo:["L'auteur dit que… (repetido)","L'auteur souligne / affirme / rappelle que…","Variar el verbo."]},[
 C("¿Qué significa «étayer»?","Il étaye son argument.",["apoyar con pruebas","debilitar","ocultar"],0,"<b>étayer</b> = fundamentar."),
 C("Elige.","Pone de relieve un problema.",["Il met en évidence un problème.","Il met en relief de un problème.","Il met évident un problème."],0,"<b>mettre en évidence</b>."),
 C("¿Qué hace un documento que «nuance» otro?","nuancer",["matiza","confirma totalmente","copia"],0,"<b>matizar</b>."),
 F("Completa.","L'article ___ sur les effets du télétravail. (trata)",["porte"],"<b>porter sur</b>."),
 F("Completa.","Ce texte remet en ___ les idées reçues.",["question","cause"],"<b>remettre en question</b>."),
 Mt("Une cada verbo con su función.","Verbo → función",[["aborder","presentar un tema"],["mettre en lumière","mostrar"],["souligner","destacar"],["réfuter","rechazar un argumento"]],"Verbos de análisis."),
 S("Clasifica.","Actitud del autor",["Acepta / apoya","Discute / rechaza"],[["confirmer",0],["étayer",0],["corroborer",0],["appuyer",0],["réfuter",1],["remettre en cause",1],["contester",1],["nuancer",1]],"Posición frente a una idea."),
 P("Encuentra la palabra incorrecta y corrígela.","Cette enquête met en [évidente] les inégalités d'accès aux soins .","évidence","<b>mettre en évidence</b>."),
 O("Ordena: «El autor matiza esta idea».",["L'auteur","nuance","cette","idée"],"<i>L'auteur nuance cette idée.</i>"),
 D("Le premier document met en lumière le problème ; le second en nuance la portée.")]),
L("prog-connecteurs-soutenus","Connecteurs soutenus : dès lors, a fortiori, en l'occurrence, à cet égard","coh",{
 idea:"El texto C1 usa conectores cultos y precisos: dès lors (por consiguiente / desde ese momento), a fortiori (con mayor razón), en l'occurrence (en este caso concreto), à cet égard (a este respecto), de surcroît (además), partant (por tanto, muy culto), qui plus est (y lo que es más), certes… il n'en demeure pas moins que (no es menos cierto que).",
 para:"Para dar precisión lógica y registro a la síntesis y al ensayo.",
 regla:["Consecuencia: <i>dès lors, par conséquent, partant, de ce fait</i>.","Refuerzo: <i>a fortiori, qui plus est, de surcroît</i>.","Precisión: <i>en l'occurrence, à cet égard, en la matière</i>.","Concesión fuerte: <i>il n'en demeure pas moins que, toujours est-il que</i> (+ ind.).","Evitar repetir <i>donc, mais, aussi</i>."],
 ej:[["Les ressources sont limitées ; dès lors, il faut établir des priorités.","Los recursos son limitados; por consiguiente, hay que fijar prioridades."],["Si les adultes peinent, a fortiori les enfants.","Si los adultos tienen dificultades, con mayor razón los niños."],["Certes, le coût est élevé ; il n'en demeure pas moins que le projet est utile.","Es cierto que el coste es alto; no es menos cierto que el proyecto es útil."]],
 ojo:["à fortiori (con acento)","a fortiori","Latinismo sin acento (se tolera <i>à</i>)."]},[
 C("¿Qué significa «a fortiori»?","a fortiori",["con mayor razón","por la fuerza","al principio"],0,"<b>con mayor razón</b>."),
 C("¿Qué significa «en l'occurrence»?","en l'occurrence",["en este caso concreto","por casualidad","en cambio"],0,"<b>en este caso</b>."),
 C("Elige.","No es menos cierto que…",["Il n'en demeure pas moins que…","Il ne demeure pas moins de que…","Il en demeure moins que…"],0,"Fórmula fija."),
 F("Completa.","Le budget est réduit ; dès ___ , certains projets seront abandonnés.",["lors"],"<b>dès lors</b>."),
 F("Completa.","C'est cher et, qui plus ___ , inefficace.",["est"],"<b>qui plus est</b>."),
 Mt("Une cada conector con su función.","Conector → función",[["dès lors","consecuencia"],["de surcroît","adición"],["à cet égard","precisión"],["toujours est-il que","concesión"]],"Conectores cultos."),
 S("Clasifica.","Función",["Consecuencia","Adición"],[["dès lors",0],["de ce fait",0],["partant",0],["par conséquent",0],["de surcroît",1],["qui plus est",1],["en outre",1],["par ailleurs",1]],"Dos familias."),
 P("Encuentra la palabra incorrecta y corrígela.","Les adultes ont du mal ; [à] fortiori les enfants , qui débutent .","a","Latinismo: <b>a fortiori</b> (sin acento)."),
 O("Ordena: «A este respecto, el informe es claro».",["À cet égard,","le rapport","est","clair"],"<i>À cet égard, le rapport est clair.</i>"),
 D("Les ressources sont limitées ; dès lors, il convient d'établir des priorités.")])
])
]);

var S8=Sec("C1.1·8","Méthodes universitaires","Leer un artículo científico, problematizar, introducir y concluir, transiciones, tipos de argumentos, bibliografía, plagio, definir conceptos, confrontar documentos y titular.",[
U("Leer y plantear",[
L("prog-article-scientifique","Lire un article scientifique","co",{
 idea:"Un artículo científico sigue una estructura fija (IMRaD en francés: introduction, méthodes, résultats, discussion) con resumen (résumé / abstract) y palabras clave. Leerlo bien es ir primero al resumen, la introducción y la conclusión, y luego a los resultados.",
 para:"Para aprovechar la bibliografía universitaria en francés.",
 regla:["Partes: <i>résumé, mots-clés, introduction, méthodologie, résultats, discussion, conclusion, bibliographie</i>.","Lectura estratégica: resumen → introducción (problema) → conclusión → resultados.","Marcadores: <i>Cette étude vise à…, Nos résultats montrent que…, Ces données suggèrent que…, Une limite de cette étude…</i>","Vocabulario: <i>un échantillon (muestra), une variable, un corpus, une enquête, significatif</i>."],
 ej:[["Cette étude vise à évaluer l'effet du sommeil sur la mémoire.","Este estudio pretende evaluar el efecto del sueño en la memoria."],["L'échantillon comprend 500 étudiants.","La muestra comprende 500 estudiantes."],["Une limite de cette étude tient à la taille du corpus.","Una limitación de este estudio se debe al tamaño del corpus."]],
 ojo:["un échantillon = un escaparate","un échantillon = una muestra","Término metodológico."]},[
 C("¿Qué es «un échantillon»?","l'échantillon de l'enquête",["la muestra","el escalón","el resultado"],0,"<b>muestra</b>."),
 C("¿Qué leer primero?","Lectura estratégica",["el resumen","la bibliografía","los anexos"],0,"<b>Résumé</b>."),
 C("¿Qué introduce «Cette étude vise à…»?","Cette étude vise à…",["el objetivo","los resultados","las limitaciones"],0,"<b>Objetivo</b>."),
 F("Completa.","Nos ___ montrent une nette amélioration. (resultados)",["résultats"],"<b>résultats</b>."),
 F("Completa.","Une ___ de cette étude est la petite taille de l'échantillon. (limitación)",["limite"],"<b>limite</b>."),
 Mt("Une cada parte con su contenido.","Parte → contenido",[["résumé","síntesis del artículo"],["méthodologie","cómo se investigó"],["résultats","lo que se encontró"],["discussion","interpretación y límites"]],"Estructura IMRaD."),
 S("Clasifica.","¿En qué parte aparece?",["Introducción","Discusión"],[["Cette étude vise à…",0],["La question de recherche est…",0],["Peu de travaux ont étudié…",0],["Nous faisons l'hypothèse que…",0],["Ces résultats suggèrent que…",1],["Une limite de cette étude…",1],["Des recherches futures devraient…",1],["Contrairement à X, nous observons…",1]],"Partes del artículo."),
 P("Encuentra la palabra incorrecta y corrígela.","L'[échantillion] comprend deux cents participants .","échantillon","<b>échantillon</b>."),
 O("Ordena: «Nuestros resultados sugieren que…».",["Nos","résultats","suggèrent","que…"],"<i>Nos résultats suggèrent que…</i>"),
 D("Cette étude vise à mesurer l'impact des écrans sur le sommeil des adolescents.")]),
L("prog-problematiser","Problématiser un sujet au niveau C1","struct",{
 idea:"Problematizar es transformar un tema en una pregunta que revela una tensión o paradoja: El teletrabajo → ¿Libera al trabajador o difumina la frontera entre vida privada y profesional? Se parte de una constatación, se señala la contradicción y se formula la pregunta.",
 para:"Para dar sentido y dirección a la síntesis y al ensayo DALF.",
 regla:["1. Constatación: <i>On observe depuis dix ans…</i>","2. Tensión: <i>Or, / Pourtant, / Mais cette évolution soulève…</i>","3. Pregunta: <i>Dès lors, on peut se demander dans quelle mesure…</i>","Formas: <i>Dans quelle mesure… ? En quoi… ? Faut-il… ? Peut-on… sans… ?</i>","Evitar preguntas cerradas o múltiples."],
 ej:[["Le numérique facilite l'accès au savoir ; pourtant, il fragilise l'attention.","Lo digital facilita el acceso al saber; sin embargo, debilita la atención."],["Dès lors, on peut se demander en quoi l'école doit s'adapter.","Por tanto, cabe preguntarse en qué debe adaptarse la escuela."],["Peut-on protéger l'environnement sans freiner l'économie ?","¿Se puede proteger el medio ambiente sin frenar la economía?"]],
 ojo:["Qu'est-ce que le télétravail ?","Le télétravail libère-t-il vraiment les salariés ?","Una problemática plantea una <b>tensión</b>."]},[
 C("Elige la mejor problemática.","Tema: la IA en la universidad",["L'IA menace-t-elle l'apprentissage ou le transforme-t-elle ?","Qu'est-ce que l'IA ?","L'IA existe-t-elle ?"],0,"<b>Tensión</b>."),
 C("¿Qué conector introduce la tensión?","Constatación → tensión",["Or,","Ainsi,","Par exemple,"],0,"<b>Or</b>."),
 C("Elige.","¿En qué…?",["En quoi… ?","Dans quoi… ?","Pour quoi que… ?"],0,"<b>En quoi</b>."),
 F("Completa.","Dès lors, on peut se ___ dans quelle mesure…",["demander"],"<b>se demander</b>."),
 F("Completa.","Peut-on développer le tourisme ___ détruire les sites ?",["sans"],"<b>sans</b>."),
 Mt("Une cada paso con su fórmula.","Paso → fórmula",[["constatación","On observe que…"],["tensión","Pourtant, …"],["pregunta","Dès lors, dans quelle mesure… ?"],["anuncio","Nous verrons d'abord…"]],"Construir la problemática."),
 S("Clasifica.","¿Problemática C1?",["Sí","No"],[["Dans quelle mesure l'école réduit-elle les inégalités ?",0],["En quoi le sport est-il politique ?",0],["Peut-on être libre sans règles ?",0],["Faut-il limiter la liberté d'expression en ligne ?",0],["Quand l'école a-t-elle été créée ?",1],["Aimez-vous le sport ?",1],["Qu'est-ce qu'une règle ?",1],["Internet existe-t-il ?",1]],"Abierta y tensa."),
 P("Encuentra la palabra incorrecta y corrígela.","On peut se demander [dans] quoi cette réforme est nécessaire .","en","<b>en quoi</b>."),
 O("Ordena la pregunta.",["Dans quelle mesure","le numérique","transforme-t-il","l'école ?"],"<i>Dans quelle mesure le numérique transforme-t-il l'école ?</i>"),
 D("Dès lors, on peut se demander dans quelle mesure le progrès rend l'humanité plus libre.")]),
L("prog-introduction","Rédiger une introduction académique","struct",{
 idea:"La introducción académica sigue un embudo: accroche (entrada: dato, cita, hecho), présentation du sujet (contexto y definición de términos), problématique y annonce du plan. Debe ocupar un 10-15 % del texto y no dar todavía los argumentos.",
 para:"Para empezar síntesis y ensayos con método.",
 regla:["<b>Accroche</b>: <i>Selon l'INSEE, … / « … », écrivait Camus. / En 2020, …</i>","<b>Sujet</b>: presentar y definir: <i>Par « X », on entend…</i>","<b>Problématique</b>: <i>Dès lors, on peut se demander…</i>","<b>Plan</b>: <i>Nous verrons dans un premier temps…, puis…</i>","Sin opinión personal todavía; sin ejemplos desarrollados."],
 ej:[["Par « mobilité douce », on entend les déplacements non motorisés.","Por «movilidad suave» se entiende los desplazamientos no motorizados."],["En 2023, plus de la moitié des actifs télétravaillaient au moins un jour.","En 2023, más de la mitad de los activos teletrabajaban al menos un día."],["Nous verrons d'abord…, avant d'examiner…","Veremos primero…, antes de examinar…"]],
 ojo:["Dans cette introduction je vais dire mon avis.","Nous nous interrogerons sur…","Sin opinión en la introducción."]},[
 C("¿Qué va primero?","Orden",["la accroche","el plan","la conclusión"],0,"<b>Accroche</b>."),
 C("Elige la definición de término.","Definir",["Par « mobilité », on entend…","Mobilité, c'est quoi ?","La mobilité, bon…"],0,"<b>on entend</b>."),
 C("¿Qué NO va en la introducción?","Prohibido",["los argumentos desarrollados","la problemática","el plan"],0,"<b>Argumentos</b>."),
 F("Completa.","Par « précarité », on ___ une situation instable.",["entend"],"<b>on entend</b>."),
 F("Completa.","Nous verrons dans un premier ___ les causes.",["temps"],"<b>dans un premier temps</b>."),
 Mt("Une cada parte con su ejemplo.","Parte → ejemplo",[["accroche","« L'homme est un loup pour l'homme », disait Hobbes."],["définition","Par « solidarité », on entend…"],["problématique","Dès lors, peut-on… ?"],["annonce du plan","Nous verrons d'abord…, puis…"]],"Embudo."),
 S("Clasifica.","¿Accroche adecuada?",["Adecuada","Inadecuada"],[["Une statistique récente",0],["Une citation pertinente",0],["Un fait d'actualité",0],["Une question provocatrice",0],["Depuis toujours, l'homme…",1],["Je vais parler de…",1],["Dans ce texte, blablabla",1],["Bonjour, voici mon essai",1]],"Evitar tópicos."),
 P("Encuentra la palabra incorrecta y corrígela.","Par « inclusion » , on [comprendre] l'accueil de tous les élèves .","entend","<b>on entend</b>."),
 O("Ordena el anuncio del plan.",["Nous verrons","d'abord","les causes,","puis les solutions"],"<i>Nous verrons d'abord les causes, puis les solutions.</i>"),
 D("Par « transition écologique », on entend le passage à un modèle économique durable.")]),
L("prog-conclusion","Rédiger une conclusion académique","struct",{
 idea:"La conclusión responde a la problemática, resume el recorrido (sin repetir frases) y abre una perspectiva (ouverture) hacia una cuestión vecina. No introduce argumentos nuevos.",
 para:"Para cerrar con fuerza la síntesis o el ensayo.",
 regla:["<b>Bilan</b>: <i>Au terme de cette analyse, il apparaît que…</i>","<b>Réponse</b>: <i>Ainsi, … permet certes…, mais…</i>","<b>Ouverture</b>: <i>Reste à savoir si…; On peut dès lors se demander si…</i>","Extensión: 10 % del texto.","Prohibido: argumentos nuevos, «En conclusión, como he dicho…»."],
 ej:[["Au terme de cette réflexion, il apparaît que le télétravail est une chance sous conditions.","Al término de esta reflexión, parece que el teletrabajo es una oportunidad bajo condiciones."],["Reste à savoir si les entreprises sauront s'adapter.","Queda por saber si las empresas sabrán adaptarse."],["En définitive, la question n'est pas tant… que…","En definitiva, la cuestión no es tanto… como…"]],
 ojo:["Un nuevo argumento en la conclusión","Solo balance, respuesta y apertura","No añadir ideas nuevas."]},[
 C("¿Qué NO va en la conclusión?","Prohibido",["un argumento nuevo","la respuesta","la apertura"],0,"<b>Nada nuevo</b>."),
 C("Elige el balance.","Balance",["Au terme de cette analyse, il apparaît que…","Pour commencer…","Premièrement…"],0,"Fórmula de cierre."),
 C("Elige la apertura.","Apertura",["Reste à savoir si…","Tout d'abord,","Par exemple,"],0,"<b>Ouverture</b>."),
 F("Completa.","Au ___ de cette réflexion, … (término)",["terme"],"<b>Au terme de</b>."),
 F("Completa.","En ___ , la question n'est pas tant technique que politique. (definitiva)",["définitive"],"<b>En définitive</b>."),
 Mt("Une cada parte con su función.","Parte → función",[["bilan","resumir el recorrido"],["réponse","responder la problemática"],["ouverture","abrir una nueva cuestión"],["registre","impersonal y prudente"]],"Conclusión."),
 S("Clasifica.","¿Introducción o conclusión?",["Introducción","Conclusión"],[["accroche",0],["annonce du plan",0],["définition des termes",0],["problématique",0],["bilan",1],["réponse",1],["ouverture",1],["Reste à savoir si…",1]],"Principio y final."),
 P("Encuentra la palabra incorrecta y corrígela.","Reste [de] savoir si cette solution sera durable .","à","<b>Reste à savoir</b>."),
 O("Ordena: «Queda por saber si…».",["Reste","à","savoir","si…"],"<i>Reste à savoir si…</i>"),
 D("Au terme de cette analyse, il apparaît que la réforme est nécessaire mais insuffisante.")])
]),
U("Argumentar con rigor",[
L("prog-transitions","Les transitions entre les parties","coh",{
 idea:"La transición cierra una parte y anuncia la siguiente: Si X présente des avantages indéniables, il comporte aussi des limites qu'il convient d'examiner. Asegura la continuidad lógica del texto y muestra al corrector que sigues un plan.",
 para:"Para que tu desarrollo avance con fluidez.",
 regla:["Estructura: <b>balance de la parte anterior + anuncio de la siguiente</b>.","<i>Si… , il n'en reste pas moins que…</i>","<i>Après avoir examiné…, il convient à présent de…</i>","<i>Au-delà de…, se pose la question de…</i>","Colocar al final de la parte o al inicio de la siguiente."],
 ej:[["Après avoir analysé les causes, il convient à présent d'envisager les solutions.","Tras analizar las causas, conviene ahora considerar las soluciones."],["Si le numérique facilite l'accès au savoir, il soulève aussi des inquiétudes.","Si lo digital facilita el acceso al saber, también suscita inquietudes."],["Au-delà de l'aspect économique, se pose la question éthique.","Más allá del aspecto económico, se plantea la cuestión ética."]],
 ojo:["Deuxième partie : …","Après avoir examiné…, il convient de…","En el texto no se titulan las partes: se enlazan."]},[
 C("Elige la transición.","Pasar de causas a soluciones",["Après avoir analysé les causes, il convient d'envisager les solutions.","Deuxième partie : les solutions.","Bon, maintenant les solutions."],0,"Balance + anuncio."),
 C("Elige.","Más allá de…",["Au-delà de…","Au-dessus de…","En delà de…"],0,"<b>Au-delà de</b>."),
 C("¿Qué dos elementos tiene una transición?","Transición",["balance y anuncio","ejemplo y cita","título y subtítulo"],0,"<b>Balance + anuncio</b>."),
 F("Completa.","Après ___ examiné les avantages, voyons les limites.",["avoir"],"<b>Après avoir</b>."),
 F("Completa.","Il convient à ___ d'étudier les conséquences. (ahora)",["présent"],"<b>à présent</b>."),
 Mt("Une cada comienzo con su final.","Transición",[["Si ce modèle a des atouts,","il présente aussi des limites."],["Après avoir vu les causes,","examinons les effets."],["Au-delà de l'aspect financier,","se pose la question humaine."],["Ce constat établi,","il reste à proposer des solutions."]],"Transiciones."),
 S("Clasifica.","¿Transición o conclusión final?",["Transición","Conclusión"],[["Il convient à présent de…",0],["Après avoir examiné…",0],["Voyons maintenant…",0],["Au-delà de cet aspect…",0],["Au terme de cette analyse…",1],["En définitive…",1],["Reste à savoir si…",1],["Pour conclure…",1]],"Entre partes o al final."),
 P("Encuentra la palabra incorrecta y corrígela.","Après avoir [analyser] les causes , examinons les conséquences .","analysé","Infinitivo pasado: <b>avoir analysé</b>."),
 O("Ordena la transición.",["Après avoir vu","les avantages,","examinons","les limites"],"<i>Après avoir vu les avantages, examinons les limites.</i>"),
 D("Après avoir analysé les causes du phénomène, il convient à présent d'en examiner les conséquences.")]),
L("prog-types-arguments","Les types d'arguments : autorité, exemple, analogie, chiffres","struct",{
 idea:"Un argumento puede apoyarse en distintos tipos de pruebas: el argumento de autoridad (un experto, una institución), el ejemplo, los datos (cifras, estudios), la analogía (comparación), la lógica causal (si… entonces) y el argumento ético (valores). Variar los tipos convence más.",
 para:"Para construir una argumentación sólida y variada.",
 regla:["<b>Autoridad</b>: <i>Comme le souligne l'OMS, …</i>","<b>Datos</b>: <i>Selon une étude de 2023, 60 % des…</i>","<b>Ejemplo</b>: <i>Ainsi, en Finlande, …</i>","<b>Analogía</b>: <i>De même que…, de même…</i>","<b>Causal</b>: <i>Si…, alors…; Puisque…, …</i>","<b>Ético</b>: <i>Au nom de l'égalité, …</i>"],
 ej:[["Comme le rappelle l'UNESCO, l'éducation est un droit.","Como recuerda la UNESCO, la educación es un derecho."],["De même qu'on apprend à lire, on doit apprendre à s'informer.","Así como se aprende a leer, hay que aprender a informarse."],["Ainsi, en Finlande, les élèves ont peu de devoirs.","Así, en Finlandia, los alumnos tienen pocos deberes."]],
 ojo:["Un solo tipo de argumento repetido","Variar autoridad, datos, ejemplos…","La variedad convence."]},[
 C("¿Qué tipo de argumento es?","Selon l'OMS, …",["autoridad","analogía","ético"],0,"<b>Autoridad</b>."),
 C("¿Qué tipo es?","De même qu'un jardin s'entretient, une langue se pratique.",["analogía","datos","autoridad"],0,"<b>Analogía</b>."),
 C("¿Qué tipo es?","60 % des jeunes lisent en ligne.",["datos","ético","ejemplo personal"],0,"<b>Cifras</b>."),
 F("Completa.","De même qu'on apprend à nager, de ___ on apprend à débattre.",["même"],"<b>de même que… de même</b>."),
 F("Completa.","Au ___ de la liberté, certains refusent cette loi.",["nom"],"<b>au nom de</b>."),
 Mt("Une cada argumento con su tipo.","Ejemplo → tipo",[["Comme le montre Bourdieu…","autoridad"],["Ainsi, au Japon…","ejemplo"],["Selon l'INSEE, 30 %…","datos"],["Au nom de la dignité…","ético"]],"Tipología."),
 S("Clasifica.","¿Prueba objetiva o valor?",["Prueba (hechos)","Valor (ética)"],[["une statistique",0],["une étude scientifique",0],["un exemple historique",0],["un rapport officiel",0],["au nom de la justice",1],["par respect de la dignité",1],["pour l'égalité",1],["au nom de la liberté",1]],"Hechos y valores."),
 P("Encuentra la palabra incorrecta y corrígela.","Comme le [souligna] l'OMS dans son dernier rapport , le sucre est dangereux .","souligne","Comentario de fuente: presente <b>souligne</b>."),
 O("Ordena: «Como recuerda la UNESCO…».",["Comme","le rappelle","l'UNESCO,","…"],"<i>Comme le rappelle l'UNESCO, …</i>"),
 D("Comme le souligne un rapport récent, l'accès aux soins reste inégal selon les régions.")]),
L("prog-bibliographie","Citer une bibliographie selon les normes","ponct",{
 idea:"La bibliografía francesa suele seguir este orden: NOM, Prénom, Titre en italique, Lieu, Éditeur, année, pages. Para artículos: NOM, Prénom, « Titre de l'article », Revue, vol., n°, année, p. x-y. En el texto: (Bourdieu, 1979, p. 12).",
 para:"Para presentar trabajos universitarios en Francia.",
 regla:["Libro: <i>BOURDIEU, Pierre, <i>La Distinction</i>, Paris, Minuit, 1979.</i>","Artículo: <i>DUPONT, Marie, « Titre », <i>Revue</i>, n° 12, 2020, p. 45-60.</i>","Web: <i>… [en ligne], URL, consulté le 3 mai 2024.</i>","En el texto: (Autor, año, página).","<i>Op. cit.</i> (obra citada), <i>ibid.</i> (misma obra), <i>et al.</i> (y otros)."],
 ej:[["(Bourdieu, 1979, p. 45)","(Bourdieu, 1979, p. 45)"],["Ibid., p. 50.","Ibid., p. 50."],["MARTIN, Luc et al., Sociologie de l'école, Paris, PUF, 2018.","MARTIN, Luc et al., …"]],
 ojo:["Titre du livre entre comillas","Titre du livre en italique; artículo entre « »","Libro en cursiva, artículo entre comillas."]},[
 C("¿Qué significa «ibid.»?","Ibid., p. 12.",["misma obra que la cita anterior","obra diferente","bibliografía completa"],0,"<b>ibidem</b>."),
 C("¿Cómo se escribe el título de un libro?","Libro",["en cursiva","entre comillas","en mayúsculas"],0,"<b>Cursiva</b>."),
 C("¿Cómo se escribe el título de un artículo?","Artículo",["entre comillas « »","en cursiva","subrayado"],0,"<b>« »</b>."),
 F("Completa.","DUPONT et ___ (= y otros)",["al."],"<b>et al.</b>"),
 F("Completa la referencia web.","… [en ligne], consulté le 3 mai 2024. → la fecha de ___",["consultation"],"<b>consultation</b>."),
 Mt("Une cada abreviatura con su sentido.","Abreviatura → sentido",[["op. cit.","obra ya citada"],["ibid.","misma obra, cita anterior"],["et al.","y otros"],["p.","página"]],"Abreviaturas."),
 S("Clasifica.","¿Cursiva o comillas?",["Cursiva","Comillas « »"],[["un livre",0],["une revue",0],["un journal (título)",0],["un film",0],["un article",1],["un chapitre",1],["un poème dans un recueil",1],["une citation",1]],"Tipografía."),
 P("Encuentra la palabra incorrecta y corrígela.","Voir DUPONT , op. cit. , [pagina] 45 .","p.","Abreviatura francesa: <b>p.</b>"),
 O("Ordena la referencia.",["BOURDIEU, Pierre,","La Distinction,","Paris, Minuit,","1979"],"Nombre, título, lugar y editorial, año."),
 D("Comme l'écrit Bourdieu dans La Distinction, les goûts sont socialement construits.")]),
L("prog-plagiat","Paraphrase, citation et plagiat","ponct",{
 idea:"En la universidad francesa el plagio (plagiat) se sanciona duramente. Hay tres formas legítimas de usar una fuente: la cita literal entre comillas con referencia, la paráfrasis (reformular con tus palabras + referencia) y el resumen. Copiar sin comillas ni fuente, aunque cambies algunas palabras, es plagio.",
 para:"Para usar fuentes con honestidad académica.",
 regla:["<b>Cita</b>: texto exacto entre « » + (Autor, año, p.).","<b>Paráfrasis</b>: otra estructura y vocabulario + referencia.","<b>Plagio</b>: copiar o casi copiar sin citar.","Integrar: <i>Selon X, … ; Comme l'affirme X, « … »</i>.","Citas largas (+ 3 líneas): en bloque con sangría."],
 ej:[["Comme l'écrit Camus, « il faut imaginer Sisyphe heureux ».","Como escribe Camus, «hay que imaginar a Sísifo feliz»."],["Selon Camus, l'homme peut trouver le bonheur dans l'effort même (1942).","Según Camus, el hombre puede encontrar la felicidad en el esfuerzo mismo."],["Le plagiat peut entraîner l'exclusion de l'université.","El plagio puede conllevar la expulsión de la universidad."]],
 ojo:["Cambiar dos palabras y no citar","Reformular de verdad + citar la fuente","Si no hay fuente, es plagio."]},[
 C("¿Qué es plagio?","Plagio",["copiar sin comillas ni referencia","citar con comillas y fuente","parafrasear citando"],0,"<b>Sin fuente</b>."),
 C("¿Qué necesita una paráfrasis?","Paráfrasis",["otras palabras + referencia","las mismas palabras sin comillas","nada"],0,"<b>Reformular + citar</b>."),
 C("¿Cómo se marca una cita literal?","Cita",["con « » y referencia","en negrita","sin marca"],0,"<b>Comillas</b>."),
 F("Completa.","Le ___ est sanctionné par l'université. (plagio)",["plagiat"],"<b>plagiat</b>."),
 F("Completa.","Comme l'___ Camus, « … ». (escribe)",["écrit"],"<b>écrit</b>."),
 Mt("Une cada práctica con su tipo.","Práctica → tipo",[["texto exacto entre « »","cita"],["ideas con tus palabras + fuente","paráfrasis"],["texto ajeno sin fuente","plagio"],["ideas principales condensadas","resumen"]],"Uso de fuentes."),
 S("Clasifica.","¿Legítimo o plagio?",["Legítimo","Plagio"],[["citer entre guillemets",0],["reformuler et citer la source",0],["résumer en citant l'auteur",0],["mettre la référence en note",0],["copier-coller sans source",1],["changer deux mots sans citer",1],["traduire un texte sans le dire",1],["réutiliser le devoir d'un ami",1]],"Honestidad académica."),
 P("Encuentra la palabra incorrecta y corrígela.","Copier un texte sans citer sa source , c'est du [plagio] .","plagiat","<b>plagiat</b>."),
 O("Ordena: «Según el autor…».",["Selon","l'auteur,","la liberté","est un choix"],"<i>Selon l'auteur, la liberté est un choix.</i>"),
 D("Toute citation doit être placée entre guillemets et accompagnée de sa référence.")])
]),
U("Trabajar con varios documentos",[
L("prog-definir","Définir un concept avec précision","struct",{
 idea:"Definir un concepto es esencial en la introducción y el desarrollo: se da la categoría general y el rasgo específico (La laïcité est un principe qui…), su origen o etimología si es útil, y se distingue de conceptos vecinos (À ne pas confondre avec…).",
 para:"Para evitar ambigüedades en tus textos académicos.",
 regla:["Estructura: <b>X est un / une + categoría + qui / dont…</b>","<i>Par X, on entend… / X désigne… / X renvoie à…</i>","Etimología: <i>Du latin « … », le terme signifie…</i>","Distinguir: <i>À la différence de Y, X…; Il ne faut pas confondre X et Y.</i>","Ejemplo que ilustra: <i>C'est le cas de…</i>"],
 ej:[["La laïcité désigne la séparation de l'État et des religions.","La laicidad designa la separación entre Estado y religiones."],["Du latin « educere », éduquer signifie « conduire hors de ».","Del latín «educere», educar significa «conducir fuera de»."],["À la différence de l'égalité, l'équité tient compte des besoins de chacun.","A diferencia de la igualdad, la equidad tiene en cuenta las necesidades de cada uno."]],
 ojo:["La démocratie c'est quand le peuple…","La démocratie est un régime politique dans lequel…","Categoría + rasgo específico."]},[
 C("Elige la definición académica.","Definir «démocratie»",["La démocratie est un régime politique dans lequel le peuple exerce le pouvoir.","La démocratie, c'est quand les gens votent.","La démocratie, c'est bien."],0,"<b>Categoría + rasgo</b>."),
 C("Elige.","X designa…",["X désigne…","X dessine…","X signe…"],0,"<b>désigner</b>."),
 C("Elige para distinguir.","A diferencia de…",["À la différence de…","En différence de…","Au différent de…"],0,"<b>À la différence de</b>."),
 F("Completa.","Ce terme ___ à l'idée de partage. (remite)",["renvoie"],"<b>renvoyer à</b>."),
 F("Completa.","Il ne faut pas ___ égalité et équité. (confundir)",["confondre"],"<b>confondre</b>."),
 Mt("Une cada fórmula con su función.","Fórmula → función",[["X désigne…","definir"],["Du latin…","etimología"],["À la différence de Y,","distinguir"],["C'est le cas de…","ilustrar"]],"Definir."),
 S("Clasifica.","¿Definición precisa?",["Precisa","Vaga"],[["un régime politique dans lequel…",0],["un principe juridique qui…",0],["un processus par lequel…",0],["un ensemble de pratiques qui…",0],["un truc qui…",1],["c'est quand…",1],["une chose un peu…",1],["un machin pour…",1]],"Rigor."),
 P("Encuentra la palabra incorrecta y corrígela.","La démocratie est un régime politique [dont] lequel le peuple exerce le pouvoir .","dans","<b>dans lequel</b>."),
 O("Ordena la definición.",["La laïcité","désigne","la séparation","de l'État et des religions"],"<i>La laïcité désigne la séparation de l'État et des religions.</i>"),
 D("Par « développement durable », on entend un développement qui répond aux besoins du présent.")]),
L("prog-confronter","Confronter des documents pour la synthèse","struct",{
 idea:"La síntesis del DALF confronta varios documentos: hay que identificar lo que dicen en común, en qué se oponen o se complementan, y organizarlo por ideas (no documento por documento). Herramienta clave: el tableau de confrontation (cuadro ideas × documentos).",
 para:"Para preparar la síntesis del DALF C1.",
 regla:["1. Leer y anotar la idea principal de cada documento.","2. Cuadro: <b>ideas en filas, documentos en columnas</b>.","3. Agrupar: convergencias, divergencias, complementos.","4. Plan temático: cada parte trata una idea con varios documentos.","Conectores: <i>de même, à l'instar de, contrairement à, tandis que, quant à</i>."],
 ej:[["À l'instar du document 1, le document 3 souligne…","Al igual que el documento 1, el documento 3 subraya…"],["Contrairement à l'auteur du premier texte, la journaliste estime que…","A diferencia del autor del primer texto, la periodista considera que…"],["Quant au document 2, il nuance ce constat.","En cuanto al documento 2, matiza esta constatación."]],
 ojo:["Doc 1 dice… Doc 2 dice… Doc 3 dice…","Idea A (doc 1 + 3) / Idea B (doc 2 vs doc 3)","Plan <b>por ideas</b>, no por documentos."]},[
 C("¿Cómo se organiza la síntesis?","Plan",["por ideas","documento por documento","al azar"],0,"<b>Por ideas</b>."),
 C("Elige.","Al igual que…",["À l'instar de…","À l'instant de…","En instar de…"],0,"<b>À l'instar de</b>."),
 C("Elige para introducir otro documento.","En cuanto a…",["Quant au document 2, …","Quand au document 2, …","Qu'en au document 2, …"],0,"<b>Quant à</b>."),
 F("Completa.","___ au premier texte, le second défend l'idée inverse. (a diferencia de)",["Contrairement"],"<b>Contrairement</b>."),
 F("Completa.","Les documents 1 et 3 ___ sur ce point. (convergen)",["convergent"],"<b>convergent</b>."),
 Mt("Une cada relación con su conector.","Relación → conector",[["convergencia","à l'instar de"],["oposición","contrairement à"],["complemento","par ailleurs"],["matiz","toutefois"]],"Confrontar."),
 S("Clasifica.","Relación",["Convergencia","Divergencia"],[["de même",0],["à l'instar de",0],["comme le souligne aussi",0],["dans le même sens",0],["contrairement à",1],["à l'inverse",1],["tandis que",1],["en revanche",1]],"Acuerdo o desacuerdo entre fuentes."),
 P("Encuentra la palabra incorrecta y corrígela.","[Quand] au troisième document , il apporte des chiffres récents .","Quant","<b>Quant à</b>."),
 O("Ordena: «Al igual que el documento 1…».",["À l'instar","du","document 1,","…"],"<i>À l'instar du document 1, …</i>"),
 D("À l'instar du premier document, le troisième souligne les risques du télétravail.")]),
L("prog-titrer","Titrer et intituler : titres et intertitres","struct",{
 idea:"En la síntesis del DALF se pide un título; en informes y memorias, títulos de partes. Un buen título es breve, informativo y a menudo nominal: «Le télétravail : liberté ou nouvelle contrainte ?». Se puede usar dos puntos, pregunta o fórmula con juego de palabras moderado.",
 para:"Para dar título a síntesis, informes y artículos.",
 regla:["Nominal: <i>La mobilité douce en ville</i>.","Con dos puntos: <i>L'IA à l'université : menace ou outil ?</i>","Pregunta: <i>Faut-il interdire les écrans à l'école ?</i>","Breve: 4-10 palabras.","Mayúscula solo inicial (y nombres propios)."],
 ej:[["Le télétravail : entre liberté et isolement","El teletrabajo: entre libertad y aislamiento"],["Vers une école sans notes ?","¿Hacia una escuela sin notas?"],["La ville de demain : verte et solidaire ?","La ciudad del mañana: ¿verde y solidaria?"]],
 ojo:["Le Télétravail : Entre Liberté Et Isolement","Le télétravail : entre liberté et isolement","Mayúsculas solo al inicio (≠ inglés)."]},[
 C("Elige el mejor título.","Síntesis sobre el teletrabajo",["Le télétravail : liberté ou contrainte ?","Mon texte sur le travail à la maison que j'ai écrit","TÉLÉTRAVAIL"],0,"Breve e informativo."),
 C("¿Cómo van las mayúsculas en un título francés?","Mayúsculas",["solo la primera palabra y nombres propios","todas las palabras","ninguna"],0,"<b>Inicial</b>."),
 C("¿Qué estructura es?","Vers une école sans notes ?",["pregunta","nominal con dos puntos","juego de palabras"],0,"<b>Pregunta</b>."),
 F("Completa.","L'IA à l'université ___ menace ou outil ? (signo)",[":"],"<b>:</b> con espacio antes."),
 F("Completa.","___ une ville plus verte ? (hacia)",["Vers"],"<b>Vers</b>."),
 Mt("Une cada tipo con su ejemplo.","Tipo → ejemplo",[["nominal","La crise du logement"],["dos puntos","Le sport : un enjeu politique"],["pregunta","Faut-il taxer le kérosène ?"],["«entre… et…»","Le numérique, entre promesses et risques"]],"Tipos de título."),
 S("Clasifica.","¿Buen título?",["Sí","No"],[["La ville face au climat",0],["Écrans et enfance : quels risques ?",0],["Vers la fin du papier ?",0],["L'eau, un bien commun",0],["Synthèse",1],["Mon devoir",1],["Texte sur plein de choses",1],["Titre",1]],"Informativo."),
 P("Encuentra la palabra incorrecta y corrígela.","Le Télétravail : Entre [Liberté] et contrainte","liberté","Minúscula: <b>liberté</b>."),
 O("Ordena el título.",["Le télétravail :","entre liberté","et","isolement"],"<i>Le télétravail : entre liberté et isolement</i>."),
 D("L'intelligence artificielle à l'université : menace ou opportunité ?")])
])
]);

var S9=Sec("C1.1·9","Le DALF C1 en pratique","Comprensión oral larga, comprensión escrita, síntesis paso a paso, ensayo, preparación del oral, debate, gestión del tiempo, errores C1, léxico abstracto, verbos de relación lógica, autoevaluación y registro.",[
U("Comprensión",[
L("prog-co-longue","Comprendre un document oral long","co",{
 idea:"En el DALF C1 se escucha un documento largo (conferencia, debate radiofónico) dos veces. Hay que anticipar con las preguntas, tomar notas estructuradas (ideas principales, ejemplos, opiniones de cada participante) y distinguir hechos, opiniones y matices.",
 para:"Para la prueba de comprensión oral del DALF C1.",
 regla:["Antes: leer todas las preguntas y subrayar palabras clave.","1.ª escucha: estructura general, número de participantes, tesis.","2.ª escucha: detalles, cifras, matices, ejemplos.","Notas: columnas por participante o por parte; símbolos y abreviaturas.","Atención a los marcadores del orador: <i>premièrement, en revanche, j'insiste sur, pour résumer</i>."],
 ej:[["Premièrement, je voudrais rappeler le contexte.","En primer lugar, quisiera recordar el contexto."],["J'insiste sur ce point, car il est souvent négligé.","Insisto en este punto, porque a menudo se descuida."],["Pour résumer, trois idées se dégagent.","Para resumir, se desprenden tres ideas."]],
 ojo:["Intentar escribir todo","Notas por ideas y participantes","Estructura antes que detalle."]},[
 C("¿Qué hacer antes de escuchar?","Preparación",["leer todas las preguntas","cerrar los ojos","escribir la respuesta"],0,"<b>Anticipar</b>."),
 C("¿Para qué sirve la 1.ª escucha?","1.ª escucha",["captar la estructura general","anotar todas las cifras","corregir la ortografía"],0,"<b>Visión global</b>."),
 C("¿Qué anuncia «pour résumer»?","Marcador",["una recapitulación","un ejemplo","una objeción"],0,"<b>Resumen</b>."),
 F("Completa.","J'insiste ___ ce point essentiel.",["sur"],"<b>insister sur</b>."),
 F("Completa.","Trois idées se ___ de cette conférence. (desprenden)",["dégagent"],"<b>se dégager</b>."),
 Mt("Une cada marcador con su función.","Marcador → función",[["premièrement","enumerar"],["en revanche","oponer"],["j'insiste sur","destacar"],["pour résumer","recapitular"]],"Marcadores del oral."),
 S("Clasifica.","¿Hecho u opinión del orador?",["Hecho","Opinión"],[["Le taux a doublé en dix ans.",0],["La loi date de 2019.",0],["L'étude porte sur 3 000 personnes.",0],["Le projet coûte 2 millions.",0],["À mon sens, c'est une erreur.",1],["Je reste sceptique.",1],["Il me paraît essentiel de…",1],["Cette mesure est, selon moi, injuste.",1]],"Distinguir."),
 P("Encuentra la palabra incorrecta y corrígela.","Pour [résumé] , cette conférence défend trois idées .","résumer","<b>Pour résumer</b> (infinitivo)."),
 O("Ordena: «Insisto en este punto».",["J'insiste","sur","ce","point"],"<i>J'insiste sur ce point.</i>"),
 D("Pour résumer, trois idées principales se dégagent de cette intervention.")]),
L("prog-ce-c1","La compréhension écrite du DALF C1","co",{
 idea:"La comprensión escrita C1 usa un texto largo (1 500-2 000 palabras) con preguntas de opción múltiple, verdadero/falso justificado con una cita, y preguntas abiertas que piden reformular. Justificar exige copiar la frase exacta; reformular exige no copiar.",
 para:"Para responder bien a cada tipo de pregunta.",
 regla:["<b>Vrai / Faux + justification</b>: copiar la frase exacta del texto entre comillas.","<b>QCM</b>: eliminar opciones que deforman el texto.","<b>Question ouverte</b>: responder con tus palabras, frase completa.","Identificar la tesis del autor y su tono (irónico, crítico, neutro).","Buscar el sentido de palabras por el contexto."],
 ej:[["Vrai : « Le télétravail a progressé de 30 % » (l. 12).","Verdadero: «…» (línea 12)."],["L'auteur adopte un ton critique à l'égard des réseaux.","El autor adopta un tono crítico respecto a las redes."],["Selon le texte, la mesure est jugée insuffisante.","Según el texto, la medida se considera insuficiente."]],
 ojo:["Justificar con tus palabras","Justificar con la cita exacta","En V/F se <b>cita</b>; en abiertas se <b>reformula</b>."]},[
 C("¿Cómo se justifica un Vrai / Faux?","Justificar",["con la cita exacta","con tus palabras","sin justificar"],0,"<b>Cita</b>."),
 C("¿Cómo se responde a una pregunta abierta?","Pregunta abierta",["reformulando con tus palabras","copiando un párrafo","con una palabra"],0,"<b>Reformular</b>."),
 C("¿Qué tono tiene?","« Encore une réforme miracle… »",["irónico","neutro","entusiasta"],0,"<b>Ironía</b>."),
 F("Completa.","L'auteur adopte un ton critique à l'___ des réseaux. (respecto a)",["égard"],"<b>à l'égard de</b>."),
 F("Completa.","Selon le texte, la mesure est ___ insuffisante. (considerada)",["jugée"],"<b>jugée</b>."),
 Mt("Une cada tipo de pregunta con su estrategia.","Pregunta → estrategia",[["Vrai / Faux","citar la frase"],["QCM","eliminar distractores"],["question ouverte","reformular"],["sens d'un mot","usar el contexto"]],"Estrategias."),
 S("Clasifica.","Tono",["Crítico","Favorable"],[["dénoncer",0],["déplorer",0],["s'inquiéter de",0],["fustiger",0],["saluer",1],["se réjouir de",1],["louer",1],["défendre",1]],"Verbos que revelan el tono."),
 P("Encuentra la palabra incorrecta y corrígela.","L'auteur [salue] les dérives des réseaux sociaux et les condamne .","dénonce","Coherencia con <i>condamne</i>: <b>dénonce</b>."),
 O("Ordena: «El autor adopta un tono irónico».",["L'auteur","adopte","un ton","ironique"],"<i>L'auteur adopte un ton ironique.</i>"),
 D("Dans ce texte, l'auteur déplore la place croissante des écrans dans nos vies.")])
]),
U("Producción escrita",[
L("prog-synthese-etapes","La synthèse pas à pas","consigne",{
 idea:"La síntesis DALF (unas 220 palabras) exige: leer, confrontar en un cuadro, construir una problemática común, un plan temático en 2-3 partes, redactar sin opinión personal ni ejemplos externos, con título, citando los documentos de forma neutra y respetando el número de palabras.",
 para:"Para aprobar la prueba más técnica del DALF C1.",
 regla:["1. Lectura activa (15 min): idea principal de cada documento.","2. Cuadro de confrontación (15 min).","3. Problemática + plan temático (10 min).","4. Redacción (30 min): introducción breve, 2-3 partes, conclusión corta.","5. Relectura + conteo (10 min).","Prohibido: opinión personal, ideas ajenas a los documentos, citas largas."],
 ej:[["Les documents proposés abordent la question du télétravail.","Los documentos propuestos abordan la cuestión del teletrabajo."],["Si le document 1 insiste sur…, le document 2 souligne…","Si el documento 1 insiste en…, el documento 2 subraya…"],["Au total, les documents s'accordent sur…","En total, los documentos coinciden en…"]],
 ojo:["Je pense que le télétravail est génial.","Les documents s'accordent à reconnaître que…","Sin <b>opinión</b> en la síntesis."]},[
 C("¿Qué está prohibido en la síntesis?","Prohibido",["dar tu opinión","usar conectores","poner título"],0,"<b>Opinión</b>."),
 C("¿Cuántas palabras aprox.?","Extensión",["unas 220","unas 60","unas 1 000"],0,"<b>~220</b>."),
 C("¿Cómo se organiza el plan?","Plan",["temático","documento por documento","cronológico por autor"],0,"<b>Temático</b>."),
 F("Completa.","Les documents s'___ à reconnaître l'importance du sommeil. (coinciden)",["accordent"],"<b>s'accorder à</b>."),
 F("Completa.","Les documents proposés ___ la question du logement. (abordan)",["abordent"],"<b>aborder</b>."),
 Mt("Une cada paso con su duración aproximada.","Paso → tiempo",[["lectura activa","15 min"],["cuadro de confrontación","15 min (cuadro)"],["redacción","30 min"],["relectura","10 min"]],"Gestión de la prueba."),
 S("Clasifica.","¿Permitido en la síntesis?",["Permitido","Prohibido"],[["un titre",0],["des connecteurs",0],["mentionner les documents",0],["une problématique",0],["« Je pense que »",1],["un exemple personnel",1],["une idée absente des documents",1],["une longue citation",1]],"Reglas de la síntesis."),
 P("Encuentra la palabra incorrecta y corrígela.","Les trois documents s'[accorde] à reconnaître l'importance du sommeil .","accordent","Sujeto plural: <b>s'accordent</b>."),
 O("Ordena: «Los documentos abordan la cuestión de la vivienda».",["Les documents","abordent","la question","du logement"],"<i>Les documents abordent la question du logement.</i>"),
 D("Si le premier document insiste sur les avantages, le second en souligne les limites.")]),
L("prog-essai-dalf","L'essai argumenté du DALF C1","consigne",{
 idea:"Tras la síntesis, el DALF C1 pide un texto argumentado (unas 250 palabras) sobre el mismo tema: artículo, carta, ensayo… Aquí sí se da opinión, con un registro adaptado al destinatario, argumentos propios, ejemplos y refutación.",
 para:"Para la segunda parte de la producción escrita del DALF C1.",
 regla:["Leer la consigna: <b>género, destinatario, posición</b>.","Opinión clara desde la introducción o anunciada.","2-3 argumentos + ejemplos concretos (cultura, actualidad).","Refutar un contraargumento (<i>Certes… il n'en demeure pas moins que…</i>).","Adaptar el registro (carta al director, artículo para una revista…).","Firmar según el género si se pide."],
 ej:[["Contrairement à une idée répandue, le télétravail n'isole pas nécessairement.","Contrariamente a una idea extendida, el teletrabajo no aísla necesariamente."],["Certes, le coût est élevé ; il n'en demeure pas moins que l'investissement est rentable.","Es cierto que el coste es alto; no obstante, la inversión es rentable."],["C'est pourquoi j'appelle les décideurs à agir.","Por eso llamo a los responsables a actuar."]],
 ojo:["Repetir la síntesis","Aportar tus propios argumentos y ejemplos","El ensayo es <b>personal</b>."]},[
 C("¿Qué diferencia el ensayo de la síntesis?","Diferencia",["el ensayo incluye tu opinión","el ensayo no tiene plan","la síntesis tiene opinión"],0,"<b>Opinión</b>."),
 C("Elige la refutación culta.","Refutar",["Certes…, il n'en demeure pas moins que…","Mais non, c'est faux.","Bof."],0,"Concesión + refutación."),
 C("Elige la fórmula para rebatir un tópico.","Tópico",["Contrairement à une idée répandue, …","Comme tout le monde le sait, …","Évidemment, …"],0,"<b>Contrairement à une idée répandue</b>."),
 F("Completa.","Il n'en ___ pas moins que ce projet est nécessaire.",["demeure","reste"],"<b>il n'en demeure pas moins que</b>."),
 F("Completa.","J'appelle les décideurs ___ agir.",["à"],"<b>appeler à</b>."),
 Mt("Une cada género con su rasgo.","Género → rasgo",[["lettre au rédacteur","fórmulas de carta"],["article","título y entradilla"],["essai","introducción, plan, conclusión"],["discours","interpelar al público"]],"Géneros."),
 S("Clasifica.","¿Síntesis o ensayo?",["Síntesis","Ensayo"],[["sans opinion",0],["plan à partir des documents",0],["titre obligatoire",0],["mention des documents",0],["opinion personnelle",1],["exemples personnels",1],["réfutation",1],["appel à l'action",1]],"Dos pruebas distintas."),
 P("Encuentra la palabra incorrecta y corrígela.","Contrairement [de] une idée répandue , les jeunes lisent beaucoup .","à","<b>Contrairement à</b>."),
 O("Ordena: «Contrariamente a una idea extendida…».",["Contrairement","à une idée","répandue,","…"],"<i>Contrairement à une idée répandue, …</i>"),
 D("Contrairement à une idée répandue, les jeunes n'ont jamais autant lu qu'aujourd'hui.")])
]),
U("El oral C1",[
L("prog-oral-preparation","Préparer l'exposé oral du DALF C1","struct",{
 idea:"En el oral del DALF C1 tienes una hora para preparar, a partir de un dossier de documentos, una exposición de unos 10 minutos con problemática y plan, seguida de un debate de 20 minutos. No se lee: se habla a partir de notas esquemáticas.",
 para:"Para organizar la hora de preparación y la exposición.",
 regla:["Preparación (60 min): leer el dossier, problemática, plan en 2-3 partes, ejemplos, introducción y conclusión escritas en palabras clave.","Exposición (≈ 10 min): anunciar el plan, transiciones claras, mirar al jurado.","No leer: notas con palabras clave y conectores.","Tiempo: introducción 1-2 min, partes 3 min, conclusión 1 min.","Integrar los documentos y ejemplos propios."],
 ej:[["Le dossier que j'ai eu à étudier porte sur…","El dossier que tuve que estudiar trata de…"],["Je m'attacherai d'abord à montrer que…","Me dedicaré primero a mostrar que…"],["J'en viens à présent à ma deuxième partie.","Paso ahora a mi segunda parte."]],
 ojo:["Leer un texto redactado","Hablar desde notas esquemáticas","El jurado evalúa la <b>interacción</b>."]},[
 C("¿Cuánto dura la preparación?","Preparación",["1 hora","10 minutos","2 horas"],0,"<b>60 min</b>."),
 C("¿Qué NO hacer en la exposición?","Evitar",["leer un texto redactado","mirar al jurado","anunciar el plan"],0,"<b>No leer</b>."),
 C("Elige la fórmula de plan.","Anunciar",["Je m'attacherai d'abord à montrer que…","D'abord je lis mon texte.","Voilà mon texte."],0,"<b>s'attacher à</b>."),
 F("Completa.","J'en viens à ___ à ma deuxième partie. (ahora)",["présent"],"<b>à présent</b>."),
 F("Completa.","Le dossier ___ sur l'éducation numérique. (trata)",["porte"],"<b>porter sur</b>."),
 Mt("Une cada momento con su duración.","Momento → duración",[["introducción","1-2 min"],["cada parte","≈ 3 min"],["conclusión","≈ 1 min"],["debate","≈ 20 min"]],"Timing."),
 S("Clasifica.","¿Buena práctica?",["Sí","No"],[["noter des mots-clés",0],["annoncer le plan",0],["regarder le jury",0],["faire des transitions",0],["tout rédiger et lire",1],["parler trop vite",1],["ignorer les documents",1],["dépasser 20 minutes",1]],"Exposición eficaz."),
 P("Encuentra la palabra incorrecta y corrígela.","Je m'[attacherais] d'abord à définir les termes du sujet .","attacherai","Anuncio del plan: futuro <b>attacherai</b>."),
 O("Ordena: «Paso ahora a mi segunda parte».",["J'en viens","à présent","à ma","deuxième partie"],"<i>J'en viens à présent à ma deuxième partie.</i>"),
 D("Je m'attacherai d'abord à définir les enjeux, puis j'examinerai les solutions possibles.")]),
L("prog-oral-debat","Débattre avec le jury au DALF C1","struct",{
 idea:"En el debate el jurado cuestiona tu postura, pide precisiones o ejemplos y a veces defiende lo contrario. Se valora que escuches, reformules, matices, defiendas tu posición con argumentos y aceptes objeciones pertinentes.",
 para:"Para la parte de interacción del oral C1.",
 regla:["Reformular la pregunta: <i>Si je vous comprends bien, vous me demandez si…</i>","Conceder: <i>Vous soulevez là un point important.</i>","Matizar: <i>Je nuancerais toutefois en disant que…</i>","Defender: <i>Il me semble néanmoins que…</i>","Pedir tiempo: <i>C'est une question complexe ; permettez-moi d'y réfléchir.</i>"],
 ej:[["Vous soulevez là un point essentiel.","Plantea usted un punto esencial."],["Je nuancerais toutefois ce propos.","Matizaría sin embargo esta afirmación."],["Permettez-moi de préciser ma pensée.","Permítame precisar mi pensamiento."]],
 ojo:["Vous avez tort.","Je vois les choses un peu différemment.","Firmeza cortés."]},[
 C("Elige para conceder.","Conceder",["Vous soulevez là un point important.","Vous avez tort.","Je ne sais pas."],0,"Reconocer el punto."),
 C("Elige para matizar.","Matizar",["Je nuancerais toutefois…","Je refuse de répondre.","C'est faux, point."],0,"<b>nuancer</b>."),
 C("Elige para precisar.","Precisar",["Permettez-moi de préciser ma pensée.","Laissez-moi tranquille.","Je dis ce que je veux."],0,"Cortés."),
 F("Completa.","Si je vous ___ bien, vous me demandez si…",["comprends"],"<b>comprends</b>."),
 F("Completa.","Vous ___ là une question délicate. (plantea)",["soulevez"],"<b>soulever</b>."),
 Mt("Une cada fórmula con su función.","Fórmula → función",[["Si je vous comprends bien…","reformular"],["Vous soulevez un point important.","conceder"],["Je nuancerais…","matizar"],["Il me semble néanmoins…","defender"]],"Debate."),
 S("Clasifica.","¿Adecuado con el jurado?",["Adecuado","Inadecuado"],[["C'est une question complexe.",0],["Permettez-moi de nuancer.",0],["Je comprends votre objection.",0],["Vous avez raison sur ce point.",0],["N'importe quoi.",1],["Je ne veux pas répondre.",1],["Tu te trompes.",1],["Passons, c'est nul.",1]],"Registro."),
 P("Encuentra la palabra incorrecta y corrígela.","Vous [levez] là un point essentiel , je vous remercie .","soulevez","<b>soulever un point</b>."),
 O("Ordena: «Matizaría esta idea».",["Je","nuancerais","cette","idée"],"<i>Je nuancerais cette idée.</i>"),
 D("Vous soulevez là un point essentiel ; permettez-moi toutefois de nuancer.")]),
L("prog-gestion-temps","Gérer son temps le jour de l'examen","struct",{
 idea:"El DALF C1 dura casi 5 horas en total: comprensión oral (40 min), comprensión escrita (50 min), producción escrita (2 h 30), producción oral (1 h de preparación + 30 min). Gestionar el tiempo y la energía es parte del éxito.",
 para:"Para llegar al final con tiempo para releer.",
 regla:["Escrita: 1 h 15 síntesis + 1 h ensayo + 15 min relectura (orientativo).","Contar palabras al final (± 10 % tolerado).","No bloquearse en una pregunta de comprensión: volver después.","Oral: reservar 10 min para introducción y conclusión.","Llevar reloj; hidratarse; leer todas las consignas."],
 ej:[["Je consacre une heure et quart à la synthèse.","Dedico una hora y cuarto a la síntesis."],["Il me reste dix minutes pour me relire.","Me quedan diez minutos para releerme."],["J'ai compté 230 mots.","He contado 230 palabras."]],
 ojo:["Dedicar 2 h a la síntesis","Repartir el tiempo entre las dos tareas","Sin relectura se pierden puntos."]},[
 C("¿Cuánto dura la producción escrita del DALF C1?","Producción escrita",["2 h 30","1 h","4 h"],0,"<b>2 h 30</b>."),
 C("¿Qué tolerancia suele haber en el número de palabras?","Tolerancia",["± 10 %","± 50 %","ninguna"],0,"<b>± 10 %</b>."),
 C("Si una pregunta bloquea…","Estrategia",["pasar y volver después","abandonar el examen","inventar sin leer"],0,"<b>Volver después</b>."),
 F("Completa.","Je ___ une heure à la synthèse. (dedico)",["consacre"],"<b>consacrer</b>."),
 F("Completa.","Il me ___ dix minutes. (quedan)",["reste"],"<b>il me reste</b>."),
 Mt("Une cada prueba con su duración.","Prueba → duración",[["compréhension orale","≈ 40 min"],["compréhension écrite","≈ 50 min"],["production écrite","2 h 30"],["préparation orale","1 h"]],"Formato DALF C1."),
 S("Clasifica.","¿Buena gestión?",["Buena","Mala"],[["lire toutes les consignes",0],["compter les mots",0],["garder du temps pour relire",0],["porter une montre",0],["commencer sans lire la consigne",1],["passer 2 h sur la synthèse",1],["ne pas relire",1],["bloquer sur une question",1]],"Estrategia."),
 P("Encuentra la palabra incorrecta y corrígela.","Il me [restent] cinq minutes pour relire ma copie .","reste","Impersonal: <b>il me reste</b>."),
 O("Ordena: «Me quedan diez minutos».",["Il","me reste","dix","minutes"],"<i>Il me reste dix minutes.</i>"),
 D("Je garde toujours un quart d'heure pour relire ma synthèse et mon essai.")])
]),
U("Afinar el nivel C1",[
L("prog-erreurs-c1","Les erreurs qui coûtent le C1","ortho",{
 idea:"Los correctores del C1 penalizan errores que ya no se esperan: calcos del español (*assister = ayudar), registro mezclado, repeticiones, conectores mal usados (en effet para oponer), subjuntivo omitido, concordancia del participio, anglicismos y frases demasiado largas.",
 para:"Para no perder puntos por errores evitables.",
 regla:["Conectores: <i>en effet</i> justifica (no opone); <i>or</i> introduce un dato contrario; <i>par contre</i> es oral.","Subjuntivo tras <i>bien que, il faut que, avant que</i>.","Participio con <i>avoir</i> y COD antepuesto: <i>les lettres que j'ai écrites</i>.","Registro homogéneo: evitar <i>du coup, genre, ça</i> en escrito formal.","Frases de máximo 3 líneas; una idea por frase."],
 ej:[["Bien que la mesure soit coûteuse, elle est nécessaire.","Aunque la medida es costosa, es necesaria."],["Les décisions qu'il a prises ont surpris.","Las decisiones que tomó sorprendieron."],["Cependant, cette solution présente des limites.","Sin embargo, esta solución presenta límites."]],
 ojo:["Bien que la mesure est coûteuse…","Bien que la mesure soit coûteuse…","<b>bien que + subjuntivo</b>."]},[
 C("¿Qué conector opone en registro escrito?","Oposición formal",["cependant","en effet","du coup"],0,"<b>cependant</b>."),
 C("Elige.","Las cartas que escribió…",["les lettres qu'il a écrites","les lettres qu'il a écrit","les lettres qu'il a écrits"],0,"COD antepuesto fem. pl.: <b>écrites</b>."),
 C("Elige.","Aunque sea difícil…",["Bien que ce soit difficile…","Bien que c'est difficile…","Bien que ce sera difficile…"],0,"<b>+ subjuntivo</b>."),
 F("Corrige.","Il faut que nous ___ une solution. (trouver)",["trouvions"],"<b>trouvions</b>."),
 F("Corrige el conector (sin embargo, formal).","Le projet est ambitieux ; ___ , il manque de moyens.",["cependant","toutefois","néanmoins"],"<b>cependant</b>."),
 Mt("Une cada error con su corrección.","Error → corrección",[["du coup (escrito)","par conséquent"],["par contre (escrito)","en revanche"],["bien que + indicativo","bien que + subjuntivo"],["assister (= ayudar)","aider"]],"Errores C1."),
 S("Clasifica.","¿Correcto en un texto C1?",["Correcto","Error"],[["Bien qu'il soit tard,",0],["En revanche,",0],["Les idées que j'ai exposées",0],["Il convient de souligner",0],["Bien qu'il est tard,",1],["Par contre, du coup,",1],["Les idées que j'ai exposé",1],["Ça, c'est super important",1]],"Detectar."),
 P("Encuentra la palabra incorrecta y corrígela.","Les solutions que nous avons [proposé] sont réalistes .","proposées","COD antepuesto: <b>proposées</b>."),
 O("Ordena: «Aunque la medida sea costosa…».",["Bien que","la mesure","soit","coûteuse"],"<i>Bien que la mesure soit coûteuse…</i>"),
 D("Bien que les solutions proposées soient coûteuses, elles demeurent indispensables.")]),
L("prog-lexique-abstrait","Le lexique abstrait : enjeu, défi, levier, dérive","voc",{
 idea:"El discurso C1 usa sustantivos abstractos precisos: un enjeu (lo que está en juego), un défi (reto), un levier (palanca), une dérive (desviación negativa), un frein (freno), un atout (baza, ventaja), une piste (vía, idea), un constat (constatación), une démarche (enfoque, gestión).",
 para:"Para enriquecer el vocabulario de síntesis y ensayos.",
 regla:["<b>enjeu</b>: <i>L'enjeu est de taille.</i>","<b>défi</b>: <i>relever un défi</i>.","<b>levier / frein</b>: <i>un levier de croissance, un frein à l'innovation</i>.","<b>atout</b>: <i>La jeunesse est un atout.</i>","<b>dérive</b>: <i>les dérives des réseaux sociaux</i>.","<b>piste</b>: <i>explorer plusieurs pistes</i>; <b>constat</b>: <i>dresser un constat</i>."],
 ej:[["L'éducation constitue un levier essentiel contre les inégalités.","La educación constituye una palanca esencial contra las desigualdades."],["Le manque de formation est un frein à l'emploi.","La falta de formación es un freno para el empleo."],["Plusieurs pistes sont à explorer.","Hay varias vías que explorar."]],
 ojo:["un enjeu = un juego","un enjeu = lo que está en juego","Término clave del C1."]},[
 C("¿Qué es «un enjeu»?","L'enjeu est considérable.",["lo que está en juego","un juego","un premio"],0,"<b>enjeu</b>."),
 C("¿Qué es «un atout»?","Le bilinguisme est un atout.",["una ventaja","un obstáculo","un riesgo"],0,"<b>atout</b>."),
 C("¿Qué es «une dérive»?","les dérives de la télé-réalité",["desviaciones negativas","ventajas","derivadas"],0,"<b>dérive</b>."),
 F("Completa.","Il faut relever ce ___ collectif. (reto)",["défi"],"<b>défi</b>."),
 F("Completa.","La bureaucratie est un ___ à l'innovation. (freno)",["frein"],"<b>frein</b>."),
 Mt("Une cada palabra con su sentido.","Francés → español",[["un levier","una palanca"],["une piste","una vía / idea"],["un constat","una constatación"],["une démarche","un enfoque / trámite"]],"Léxico abstracto."),
 S("Clasifica.","¿Positivo o negativo?",["Positivo","Negativo"],[["un atout",0],["un levier",0],["une opportunité",0],["une avancée",0],["un frein",1],["une dérive",1],["un écueil",1],["une menace",1]],"Connotación."),
 P("Encuentra la palabra incorrecta y corrígela.","Maîtriser plusieurs langues est un véritable [frein] sur le marché du travail .","atout","Ventaja: <b>atout</b>."),
 O("Ordena: «Lo que está en juego es enorme».",["L'enjeu","est","de","taille"],"<i>L'enjeu est de taille.</i>"),
 D("L'éducation constitue un levier essentiel pour relever le défi de l'égalité.")]),
L("prog-verbes-logiques","Verbes de relation logique : découler de, relever de, reposer sur","voc",{
 idea:"En lugar de conectores, el C1 usa verbos que expresan relaciones lógicas: découler de / résulter de (resultar de), entraîner / engendrer / susciter (provocar), reposer sur (basarse en), relever de (ser competencia de, pertenecer a), s'inscrire dans (inscribirse en), tenir à (deberse a), aller de pair avec (ir de la mano).",
 para:"Para variar la expresión de la causa y la relación entre ideas.",
 regla:["Causa → efecto: <i>entraîner, provoquer, engendrer, susciter, favoriser</i>.","Efecto ← causa: <i>découler de, résulter de, provenir de, tenir à</i>.","Base: <i>reposer sur, s'appuyer sur, se fonder sur</i>.","Pertenencia: <i>relever de, s'inscrire dans</i>.","Correlación: <i>aller de pair avec, être lié à</i>."],
 ej:[["Cette crise découle de choix politiques anciens.","Esta crisis se deriva de decisiones políticas antiguas."],["Le succès du projet repose sur la confiance.","El éxito del proyecto se basa en la confianza."],["Cette question relève de la compétence de l'État.","Esta cuestión es competencia del Estado."]],
 ojo:["Ce problème découle à…","Ce problème découle de…","<b>découler de</b>."]},[
 C("Elige.","Se deriva de…",["découler de","découler à","découler sur"],0,"<b>découler de</b>."),
 C("Elige.","Se basa en…",["reposer sur","reposer de","reposer à"],0,"<b>reposer sur</b>."),
 C("¿Qué significa «aller de pair avec»?","aller de pair avec",["ir de la mano con","ir en pareja","oponerse a"],0,"<b>ir de la mano</b>."),
 F("Completa.","Cette mesure s'inscrit ___ une politique globale.",["dans"],"<b>s'inscrire dans</b>."),
 F("Completa.","Ce retard ___ à des problèmes techniques. (se debe)",["tient"],"<b>tenir à</b>."),
 Mt("Une cada verbo con su sentido.","Francés → español",[["engendrer","generar"],["relever de","ser competencia de"],["résulter de","resultar de"],["susciter","suscitar"]],"Verbos lógicos."),
 S("Clasifica.","Dirección de la relación",["Causa → efecto","Efecto ← causa"],[["entraîner",0],["provoquer",0],["engendrer",0],["favoriser",0],["découler de",1],["résulter de",1],["provenir de",1],["tenir à",1]],"Orientación del verbo."),
 P("Encuentra la palabra incorrecta y corrígela.","Le succès de l'entreprise repose [de] la qualité de ses produits .","sur","<b>reposer sur</b>."),
 O("Ordena: «Esta crisis se deriva de malas decisiones».",["Cette crise","découle","de","mauvais choix"],"<i>Cette crise découle de mauvais choix.</i>"),
 D("La réussite de cette réforme repose sur l'adhésion des citoyens.")]),
L("prog-references-culturelles","Mobiliser des références culturelles dans l'essai","struct",{
 idea:"En el ensayo C1 los ejemplos culturales dan peso: citar un autor (Montesquieu, Camus, Simone de Beauvoir), un hecho histórico (la loi de 1905, Mai 68), un dato de actualidad o una obra (film, novela). Deben ser pertinentes, breves y bien integrados, no una lista de nombres.",
 para:"Para enriquecer tus argumentos con cultura francófona y general.",
 regla:["Integrar: <i>Comme le montrait déjà Tocqueville, …; À l'image de…</i>","Contextualizar en una frase: quién, cuándo, qué.","Relacionar con el argumento: <i>Cet exemple illustre bien…</i>","Variedad: historia, literatura, ciencia, actualidad, experiencia de tu país.","Evitar: inventar citas, fechas dudosas, listas sin análisis."],
 ej:[["Comme l'écrivait Simone de Beauvoir, « on ne naît pas femme, on le devient ».","Como escribía Simone de Beauvoir, «no se nace mujer, se llega a serlo»."],["La loi de 1905 illustre bien l'attachement français à la laïcité.","La ley de 1905 ilustra bien el apego francés a la laicidad."],["À l'image de la Finlande, plusieurs pays ont réformé leur école.","A imagen de Finlandia, varios países reformaron su escuela."]],
 ojo:["Citar diez nombres sin explicar","Un ejemplo bien elegido y analizado","Calidad antes que cantidad."]},[
 C("Elige la integración correcta.","Referencia",["Comme le montrait déjà Tocqueville, la démocratie peut produire du conformisme.","Tocqueville. Hugo. Zola. Voilà.","Un auteur a dit un truc là-dessus."],0,"Integrada y relacionada."),
 C("¿Qué hacer tras el ejemplo?","Después del ejemplo",["relacionarlo con el argumento","pasar a otro sin comentar","repetirlo"],0,"<b>Analizarlo</b>."),
 C("Elige.","A imagen de…",["À l'image de…","À l'imagen de…","En image de…"],0,"<b>À l'image de</b>."),
 F("Completa.","Cet exemple ___ bien la difficulté de la réforme. (ilustra)",["illustre"],"<b>illustrer</b>."),
 F("Completa.","Comme l'___ Camus, « la vraie générosité envers l'avenir consiste à tout donner au présent ». (escribía)",["écrivait"],"<b>écrivait</b>."),
 Mt("Une cada referencia con su ámbito.","Referencia → ámbito",[["la loi de 1905","historia / laicidad"],["Le Deuxième Sexe","feminismo"],["Les Misérables","literatura / pobreza"],["l'accord de Paris","clima"]],"Referencias útiles."),
 S("Clasifica.","¿Buen uso de la referencia?",["Bueno","Malo"],[["un exemple précis et daté",0],["une citation exacte",0],["un lien clair avec l'argument",0],["une référence de ton pays expliquée",0],["une liste de noms",1],["une citation inventée",1],["une date approximative",1],["un exemple hors sujet",1]],"Pertinencia."),
 P("Encuentra la palabra incorrecta y corrígela.","Cet exemple [ilustre] parfaitement les limites du modèle .","illustre","Ortografía: <b>illustre</b> (dos l)."),
 O("Ordena: «Este ejemplo ilustra bien el problema».",["Cet exemple","illustre","bien","le problème"],"<i>Cet exemple illustre bien le problème.</i>"),
 D("Comme le montrait déjà Montesquieu, tout pouvoir a besoin d'un contre-pouvoir.")]),
L("prog-autoevaluation","S'autoévaluer avec les grilles du DALF","struct",{
 idea:"Las pruebas productivas del DALF se corrigen con grillas: respeto de la consigna, coherencia y cohesión, argumentación, riqueza léxica, corrección gramatical y registro. Usarlas para autoevaluarte te dice exactamente qué mejorar.",
 para:"Para entrenar con criterio y medir tu progreso.",
 regla:["<b>Consigne</b>: género, destinatario, extensión.","<b>Cohérence</b>: plan claro, conectores variados, transiciones.","<b>Argumentation</b>: tesis clara, argumentos + ejemplos, refutación.","<b>Lexique</b>: precisión, variedad, registro adaptado.","<b>Morphosyntaxe</b>: concordancias, tiempos, subjuntivo, estructuras complejas."],
 ej:[["J'ai respecté le nombre de mots.","He respetado el número de palabras."],["Mes connecteurs sont variés.","Mis conectores son variados."],["Je dois enrichir mon lexique.","Debo enriquecer mi léxico."]],
 ojo:["Solo contar faltas","Evaluar consigna, coherencia, léxico y gramática","La nota tiene varios criterios."]},[
 C("¿Qué criterio evalúa el uso de conectores?","Criterio",["cohérence et cohésion","respect de la consigne","phonétique"],0,"<b>Cohérence</b>."),
 C("¿Qué incluye «respect de la consigne»?","Consigna",["género, destinatario, extensión","ortografía","acento"],0,"Lo pedido."),
 C("¿Qué evalúa «lexique»?","Léxico",["precisión y variedad del vocabulario","la letra","la puntuación"],0,"<b>Vocabulario</b>."),
 F("Completa.","Je dois ___ mon lexique. (enriquecer)",["enrichir"],"<b>enrichir</b>."),
 F("Completa.","J'ai respecté le nombre de ___ .",["mots"],"<b>mots</b>."),
 Mt("Une cada criterio con una pregunta de control.","Criterio → pregunta",[["consigne","¿He escrito el género pedido?"],["cohérence","¿Hay plan y transiciones?"],["lexique","¿Evito repeticiones?"],["morphosyntaxe","¿Están bien las concordancias?"]],"Autoevaluación."),
 S("Clasifica.","¿Qué criterio?",["Cohérence","Morphosyntaxe"],[["connecteurs variés",0],["plan annoncé",0],["transitions",0],["paragraphes",0],["accord du participe",1],["subjonctif",1],["concordance des temps",1],["accord sujet-verbe",1]],"Criterios."),
 P("Encuentra la palabra incorrecta y corrígela.","Mes connecteurs sont [variées] et mes transitions sont claires .","variés","<i>Connecteurs</i> masc.: <b>variés</b>."),
 O("Ordena: «Debo enriquecer mi léxico».",["Je dois","enrichir","mon","lexique"],"<i>Je dois enrichir mon lexique.</i>"),
 D("Après chaque essai, je relis ma copie avec la grille d'évaluation du DALF.")])
])
]);

M.curso("prog",[S7,S8,S9]);})();
